import type { Persona } from "./types";

/**
 * Hand-written lifters with the outcome a coach would sign off after a real
 * intake (v3: real numbers included). The first three per track are the reference
 * cases; the rest pin down specific judgements (a deliberate reserve is not low
 * effort, a big week that recovers is not too much, fat loss needs a deficit, cramps
 * plus sweat is minerals, four coffees plus bad nights is caffeine, and so on) so
 * later rule edits can't quietly undo them. scripts/rules-sim.ts check [i] fails if
 * the engine disagrees.
 *
 * Every persona starts from a well-run base and overrides what makes it a case, so a
 * persona reads as the few facts that matter.
 */
type A = Record<string, string | string[]>;

const BASE: A = {
  sex: "male",
  age: "29",
  height_cm: "178",
  weight_kg: "82",
  body_type: "meso",
  training_age: "3_6y",
  training_pattern: "steady",
  sessions_week: "4",
  chest_sessions: "2",
  chest_hours: "1_2",
  back_sessions: "2",
  back_hours: "1_2",
  arms_sessions: "2",
  arms_hours: "1_2",
  legs_sessions: "2",
  legs_hours: "1_2",
  hard_set_habit: "push",
  effort_grind: "7",
  beat_last: "8",
  load_choice: "plan",
  program_switch: "2",
  rom_focus: "8",
  drive: "8",
  pain_limits: "2",
  brain_fog: "never",
  training_signs: ["none"],
  loop_score: "8",
  eating_phase: "gain",
  protein_g: "140_180",
  carbs_g: "250_350",
  diet_clean: "8",
  meal_skip: "2",
  sleep_hours: "7_8",
  sleep_regular: "same",
  full_nights: "8",
  wake_rested: "7",
  alcohol: "light",
  coffee: "1",
  stress: "4",
  activity_load: "3",
};

const PHYSIQUE_BASE: A = {
  ...BASE,
  physique_aim: "muscle",
  lagging_area: "arms",
  lagging_priority: "first",
  feel_target: "7",
  appetite: "normal",
  weekend_eating: "3",
};

const STRENGTH_BASE: A = {
  ...BASE,
  main_lift: "squat",
  lift_frequency: "twice",
  heavy_practice: "6",
  fail_point: "middle",
  weak_point_work: "6",
  form_breakdown: "3",
  max_testing: "few_months",
  muscle_work: "6",
  eating_phase: "maintain",
};

const physique = (over: A): A => ({ ...PHYSIQUE_BASE, ...over });
const strength = (over: A): A => ({ ...STRENGTH_BASE, ...over });

export const PERSONAS: Persona[] = [
  /* ───────────── physique ───────────── */
  {
    name: "Well-run physique lifter",
    track: "physique",
    answers: physique({}),
    expect: {
      min: 0,
      max: 2,
      primaryOneOf: ["expecting_year_one_speed"],
      mustExclude: [
        "sets_end_too_early",
        "no_forcing_function",
        "gaining_too_fast",
        "sleep_under_dose",
        "consistency_gap",
        "lagging_part_trained_last",
        "fat_loss_without_deficit",
        "protein_below_target",
        "underfuelled_sessions",
        "electrolytes_running_low",
      ],
    },
  },
  {
    name: "Typical stuck physique lifter",
    track: "physique",
    answers: physique({
      training_age: "1_3y",
      sessions_week: "3",
      chest_sessions: "1",
      chest_hours: "u1",
      arms_sessions: "3",
      arms_hours: "2_3",
      legs_sessions: "1",
      legs_hours: "u1",
      hard_set_habit: "stop",
      effort_grind: "3",
      beat_last: "3",
      load_choice: "feel",
      lagging_area: "chest",
      lagging_priority: "last",
      feel_target: "4",
      protein_g: "unknown",
      carbs_g: "unknown",
      eating_phase: "none",
      sleep_hours: "6_7",
      sleep_regular: "shifts",
      full_nights: "5",
      wake_rested: "5",
    }),
    expect: {
      min: 4,
      max: 9,
      mustInclude: ["sets_end_too_early", "no_forcing_function", "lagging_part_trained_last", "protein_unknown", "target_muscle_underdosed"],
      primaryOneOf: ["sets_end_too_early", "no_forcing_function", "lagging_part_trained_last", "no_surplus_no_growth"],
    },
  },
  {
    name: "Physique lifter who shows up but whose loop is broken",
    track: "physique",
    answers: physique({
      loop_score: "3",
      wake_rested: "3",
      stress: "7",
      drive: "4",
      full_nights: "5",
    }),
    expect: {
      min: 2,
      max: 6,
      mustInclude: ["consistency_gap"],
      primaryOneOf: ["consistency_gap", "life_is_the_limiter", "sleep_under_dose"],
      mustExclude: ["missed_dose"],
    },
  },
  {
    name: "Physique lifter who wants less fat and has no eating plan",
    track: "physique",
    answers: physique({
      physique_aim: "leaner",
      eating_phase: "none",
      appetite: "big",
      weekend_eating: "7",
      body_type: "endo",
      weight_kg: "96",
      height_cm: "176",
      protein_g: "100_140",
      carbs_g: "350_450",
    }),
    expect: {
      min: 1,
      max: 7,
      mustInclude: ["fat_loss_without_deficit"],
      primaryOneOf: ["fat_loss_without_deficit"],
      mustExclude: ["deficit_while_expecting_muscle", "no_surplus_no_growth"],
    },
  },
  {
    name: "Physique dieter whose deficit leaks",
    track: "physique",
    answers: physique({
      physique_aim: "leaner",
      eating_phase: "lose",
      appetite: "big",
      weekend_eating: "8",
      alcohol: "weekends",
    }),
    expect: {
      min: 1,
      max: 6,
      mustInclude: ["fat_loss_without_deficit"],
      primaryOneOf: ["fat_loss_without_deficit", "week_cancels_itself"],
      mustExclude: ["deficit_while_expecting_muscle"],
    },
  },
  {
    name: "Physique lifter whose bulk overshoots",
    track: "physique",
    answers: physique({
      eating_phase: "gain",
      appetite: "big",
      weekend_eating: "7",
      body_type: "endo",
      carbs_g: "o450",
      weight_kg: "92",
      alcohol: "weekends",
    }),
    expect: {
      min: 1,
      max: 5,
      mustInclude: ["gaining_too_fast"],
      primaryOneOf: ["gaining_too_fast"],
      mustExclude: ["no_surplus_no_growth", "deficit_while_expecting_muscle"],
    },
  },
  {
    name: "Physique lifter who can't eat enough to grow",
    track: "physique",
    answers: physique({
      eating_phase: "gain",
      appetite: "small",
      meal_skip: "8",
      body_type: "ecto",
      weight_kg: "62",
      height_cm: "182",
      carbs_g: "150_250",
      protein_g: "100_140",
    }),
    expect: {
      min: 1,
      max: 6,
      mustInclude: ["no_surplus_no_growth"],
      primaryOneOf: ["no_surplus_no_growth"],
      mustExclude: ["gaining_too_fast", "deficit_while_expecting_muscle"],
    },
  },
  {
    name: "Veteran physique lifter who drinks and diets for muscle",
    track: "physique",
    answers: physique({
      training_age: "over_6y",
      age: "38",
      eating_phase: "lose",
      alcohol: "often",
      wake_rested: "4",
      full_nights: "4",
      sleep_hours: "6_7",
    }),
    expect: {
      min: 2,
      max: 7,
      mustInclude: ["deficit_while_expecting_muscle", "alcohol_tax"],
      primaryOneOf: ["deficit_while_expecting_muscle", "alcohol_tax", "sleep_under_dose"],
      mustExclude: ["no_surplus_no_growth", "expecting_year_one_speed"],
    },
  },
  {
    name: "Physique dieter who does a lot of cardio and feels fine",
    track: "physique",
    answers: physique({
      physique_aim: "leaner",
      eating_phase: "lose",
      activity_load: "8",
      carbs_g: "250_350",
      protein_g: "180_220",
      weight_kg: "74",
    }),
    expect: {
      min: 0,
      max: 3,
      mustExclude: ["cardio_eating_the_budget", "underfuelled_sessions", "fat_loss_without_deficit"],
    },
  },
  {
    name: "Physique lifter with cramps who sweats a lot and eats clean",
    track: "physique",
    answers: physique({
      training_signs: ["cramps", "floaty", "water_worse"],
      activity_load: "8",
      diet_clean: "9",
      coffee: "3",
    }),
    expect: {
      min: 1,
      max: 5,
      mustInclude: ["electrolytes_running_low"],
      primaryOneOf: ["electrolytes_running_low"],
      mustExclude: ["underfuelled_sessions", "caffeine_overload"],
    },
  },
  {
    name: "Physique dieter running on almost no carbs",
    track: "physique",
    answers: physique({
      sex: "female",
      age: "31",
      height_cm: "165",
      weight_kg: "63",
      physique_aim: "leaner",
      eating_phase: "lose",
      carbs_g: "u150",
      protein_g: "100_140",
      brain_fog: "often",
      activity_load: "7",
      loop_score: "4",
      training_signs: ["floaty"],
    }),
    expect: {
      min: 1,
      max: 7,
      mustInclude: ["underfuelled_sessions"],
      primaryOneOf: ["underfuelled_sessions"],
      mustExclude: ["fat_loss_without_deficit", "electrolytes_running_low"],
    },
  },
  {
    name: "Physique lifter with a greasy diet and a sleep clock all over the place",
    track: "physique",
    answers: physique({
      diet_clean: "2",
      wake_rested: "3",
      pain_limits: "6",
      alcohol: "weekends",
      sleep_regular: "all_over",
      sleep_hours: "7_8",
      full_nights: "6",
    }),
    expect: {
      min: 2,
      max: 7,
      mustInclude: ["inflammatory_diet", "sleep_clock_drifts"],
      primaryOneOf: ["inflammatory_diet", "sleep_clock_drifts", "alcohol_tax"],
    },
  },

  /* ───────────── strength ───────────── */
  {
    name: "Well-run strength lifter",
    track: "strength",
    answers: strength({}),
    expect: {
      min: 0,
      max: 2,
      primaryOneOf: ["expecting_year_one_speed"],
      mustExclude: [
        "sets_end_too_early",
        "never_heavy_enough",
        "testing_instead_of_training",
        "main_lift_underpractised",
        "sticking_point_untrained",
        "strength_leaking_bodyweight",
        "volume_outruns_recovery",
        "caffeine_overload",
        "drive_has_faded",
      ],
    },
  },
  {
    name: "Typical stuck strength lifter",
    track: "strength",
    answers: strength({
      lift_frequency: "once",
      heavy_practice: "2",
      fail_point: "bottom",
      weak_point_work: "2",
      form_breakdown: "7",
      legs_sessions: "1",
      legs_hours: "u1",
      load_choice: "feel",
      beat_last: "4",
    }),
    expect: {
      min: 3,
      max: 8,
      mustInclude: ["main_lift_underpractised", "never_heavy_enough", "sticking_point_untrained"],
      primaryOneOf: ["main_lift_underpractised", "never_heavy_enough", "sticking_point_untrained", "no_forcing_function"],
      mustExclude: ["testing_instead_of_training", "volume_outruns_recovery"],
    },
  },
  {
    name: "Strength lifter running on empty",
    track: "strength",
    answers: strength({
      eating_phase: "lose",
      meal_skip: "8",
      carbs_g: "u150",
      loop_score: "3",
      brain_fog: "sometimes",
      weight_kg: "80",
    }),
    expect: {
      min: 2,
      max: 7,
      mustInclude: ["strength_leaking_bodyweight", "underfuelled_sessions"],
      primaryOneOf: ["strength_leaking_bodyweight", "underfuelled_sessions"],
    },
  },
  {
    name: "Strength lifter who keeps reps in reserve on purpose",
    track: "strength",
    answers: strength({
      hard_set_habit: "push",
      effort_grind: "6",
      heavy_practice: "7",
    }),
    expect: {
      min: 0,
      max: 2,
      mustExclude: ["sets_end_too_early", "failure_every_set", "never_heavy_enough"],
    },
  },
  {
    name: "Strength lifter with a big week who recovers fine",
    track: "strength",
    answers: strength({
      sessions_week: "6",
      chest_sessions: "3",
      chest_hours: "2_3",
      back_sessions: "3",
      back_hours: "2_3",
      arms_sessions: "2",
      arms_hours: "1_2",
      legs_sessions: "3",
      legs_hours: "3_4",
      loop_score: "8",
      wake_rested: "8",
      pain_limits: "1",
      drive: "9",
      sleep_hours: "8_9",
      full_nights: "9",
    }),
    expect: {
      min: 0,
      max: 2,
      mustExclude: ["volume_outruns_recovery", "drive_has_faded", "sleep_under_dose"],
    },
  },
  {
    name: "Strength lifter who changes programs now and then",
    track: "strength",
    answers: strength({
      program_switch: "6",
    }),
    expect: {
      min: 0,
      max: 2,
      mustExclude: ["program_hopping"],
    },
  },
  {
    name: "Strength lifter on four coffees whose drive has gone",
    track: "strength",
    answers: strength({
      coffee: "4plus",
      wake_rested: "3",
      full_nights: "4",
      drive: "2",
      loop_score: "4",
      stress: "8",
      training_signs: ["dizzy"],
    }),
    expect: {
      min: 3,
      max: 8,
      mustInclude: ["caffeine_overload", "drive_has_faded"],
      primaryOneOf: ["caffeine_overload", "drive_has_faded", "life_is_the_limiter", "sleep_under_dose", "consistency_gap"],
      mustExclude: ["electrolytes_running_low"],
    },
  },
  {
    name: "Older strength lifter whose protein is short",
    track: "strength",
    answers: strength({
      age: "52",
      weight_kg: "95",
      height_cm: "180",
      protein_g: "u100",
      training_age: "over_6y",
    }),
    expect: {
      min: 1,
      max: 4,
      mustInclude: ["protein_below_target"],
      primaryOneOf: ["protein_below_target"],
      mustExclude: ["protein_unknown"],
    },
  },
];
