import type { Persona } from "./types";

/**
 * Hand-written lifters with the outcome a coach would sign off after a real
 * intake. The first three per track are the reference cases; the rest pin down
 * specific judgements (a deliberate reserve is not low effort, a big week that
 * recovers is not too much, fat loss needs a deficit, and so on) so later rule
 * edits can't quietly undo them. scripts/rules-sim.ts check [i] fails if the
 * engine disagrees.
 */
export const PERSONAS: Persona[] = [
  /* ───────────── physique ───────────── */
  {
    name: "Well-run physique lifter",
    track: "physique",
    answers: {
      training_age: "3_6y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lagging_area: "shoulders_arms",
      lagging_priority: "first",
      feel_target: "7",
      muscle_frequency: "twice",
      effort_grind: "7",
      beat_last: "8",
      range_under_load: "full",
      program_switch: "2",
      pain_limits: "2",
      eating_phase: "gain",
      appetite: "normal",
      meal_skip: "2",
      protein_meals: "9",
      weekend_eating: "3",
      full_nights: "8",
      wake_rested: "7",
      alcohol: "light",
      session_energy: "7",
      stress: "4",
      activity_load: "3",
      missed_sessions: "2",
    },
    expect: {
      min: 0,
      max: 2,
      primaryOneOf: ["expecting_year_one_speed"],
      mustExclude: [
        "sets_end_too_early",
        "no_forcing_function",
        "gaining_too_fast",
        "sleep_under_dose",
        "consistency_gap",
        "lagging_part_trained_last",
        "fat_loss_without_deficit",
      ],
    },
  },
  {
    name: "Typical stuck physique lifter",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "stop",
      volume_feel: "5",
      load_choice: "usual",
      lagging_area: "chest_back",
      lagging_priority: "middle",
      feel_target: "5",
      muscle_frequency: "once",
      effort_grind: "4",
      beat_last: "4",
      range_under_load: "full",
      program_switch: "5",
      pain_limits: "3",
      eating_phase: "maintain",
      appetite: "normal",
      meal_skip: "4",
      protein_meals: "4",
      weekend_eating: "6",
      full_nights: "6",
      wake_rested: "6",
      alcohol: "light",
      session_energy: "6",
      stress: "5",
      activity_load: "3",
      missed_sessions: "3",
    },
    expect: {
      min: 3,
      max: 6,
      mustInclude: ["sets_end_too_early", "no_forcing_function", "no_surplus_no_growth"],
      // "Wherever it fits" + once a week is not the same as "trained last"
      mustExclude: [
        "failure_every_set",
        "volume_outruns_recovery",
        "restart_not_stall",
        "consistency_gap",
        "gaining_too_fast",
        "lagging_part_trained_last",
      ],
      primaryOneOf: ["sets_end_too_early", "no_forcing_function"],
    },
  },
  {
    name: "Physique lifter who calls it steady but misses often",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "stop",
      volume_feel: "4",
      load_choice: "feel",
      lagging_area: "legs",
      lagging_priority: "skipped",
      feel_target: "3",
      muscle_frequency: "varies",
      effort_grind: "3",
      beat_last: "3",
      range_under_load: "full",
      program_switch: "9",
      pain_limits: "3",
      eating_phase: "lose",
      appetite: "normal",
      meal_skip: "8",
      protein_meals: "3",
      weekend_eating: "9",
      full_nights: "3",
      wake_rested: "3",
      alcohol: "light",
      session_energy: "5",
      stress: "6",
      activity_load: "4",
      missed_sessions: "7",
    },
    expect: {
      min: 6,
      max: 10,
      mustInclude: [
        "sets_end_too_early",
        "program_hopping",
        "deficit_while_expecting_muscle",
        "week_cancels_itself",
        "sleep_under_dose",
        "consistency_gap",
        "lagging_part_trained_last",
      ],
      mustExclude: [
        "failure_every_set",
        "gaining_too_fast",
        "no_surplus_no_growth",
        "volume_outruns_recovery",
        "missed_dose",
        "alcohol_tax",
        "fat_loss_without_deficit",
      ],
      primaryOneOf: ["sets_end_too_early", "no_forcing_function", "program_hopping"],
    },
  },
  {
    name: "Physique lifter who wants less fat and has no eating plan",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "on_off",
      physique_aim: "leaner",
      hard_set_habit: "push",
      volume_feel: "5",
      load_choice: "feel",
      lagging_area: "everything",
      lagging_priority: "middle",
      feel_target: "5",
      muscle_frequency: "twice",
      effort_grind: "6",
      beat_last: "5",
      range_under_load: "full",
      program_switch: "4",
      pain_limits: "2",
      eating_phase: "none",
      appetite: "big",
      meal_skip: "3",
      protein_meals: "3",
      weekend_eating: "7",
      full_nights: "6",
      wake_rested: "5",
      alcohol: "weekends",
      session_energy: "6",
      stress: "5",
      activity_load: "3",
      missed_sessions: "4",
    },
    expect: {
      min: 2,
      max: 4,
      mustInclude: ["fat_loss_without_deficit", "protein_unknown"],
      mustExclude: ["deficit_while_expecting_muscle", "no_surplus_no_growth", "gaining_too_fast", "recomp_window_closed"],
      primaryOneOf: ["fat_loss_without_deficit"],
    },
  },
  {
    name: "Physique dieter whose deficit leaks",
    track: "physique",
    answers: {
      training_age: "3_6y",
      training_pattern: "steady",
      physique_aim: "leaner",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lagging_area: "legs",
      lagging_priority: "first",
      feel_target: "7",
      muscle_frequency: "twice",
      effort_grind: "7",
      beat_last: "7",
      range_under_load: "full",
      program_switch: "3",
      pain_limits: "2",
      eating_phase: "lose",
      appetite: "big",
      meal_skip: "2",
      protein_meals: "7",
      weekend_eating: "8",
      full_nights: "7",
      wake_rested: "6",
      alcohol: "light",
      session_energy: "6",
      stress: "5",
      activity_load: "4",
      missed_sessions: "2",
    },
    expect: {
      min: 1,
      max: 3,
      mustInclude: ["fat_loss_without_deficit"],
      // the fundamentals look clean, but "slow is normal" must not outrank a leaking diet
      mustExclude: ["expecting_year_one_speed", "deficit_while_expecting_muscle", "gaining_too_fast"],
      primaryOneOf: ["fat_loss_without_deficit"],
    },
  },
  {
    name: "Physique lifter whose bulk overshoots",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lagging_area: "everything",
      lagging_priority: "middle",
      feel_target: "6",
      muscle_frequency: "twice",
      effort_grind: "6",
      beat_last: "7",
      range_under_load: "full",
      program_switch: "3",
      pain_limits: "2",
      eating_phase: "gain",
      appetite: "big",
      meal_skip: "2",
      protein_meals: "7",
      weekend_eating: "8",
      full_nights: "7",
      wake_rested: "6",
      alcohol: "weekends",
      session_energy: "7",
      stress: "4",
      activity_load: "3",
      missed_sessions: "3",
    },
    expect: {
      min: 1,
      max: 3,
      mustInclude: ["gaining_too_fast"],
      mustExclude: ["no_surplus_no_growth", "deficit_while_expecting_muscle", "fat_loss_without_deficit", "week_cancels_itself"],
      primaryOneOf: ["gaining_too_fast"],
    },
  },
  {
    name: "Physique lifter who can't eat enough to grow",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lagging_area: "shoulders_arms",
      lagging_priority: "first",
      feel_target: "6",
      muscle_frequency: "twice",
      effort_grind: "7",
      beat_last: "7",
      range_under_load: "full",
      program_switch: "3",
      pain_limits: "2",
      eating_phase: "gain",
      appetite: "small",
      meal_skip: "6",
      protein_meals: "5",
      weekend_eating: "3",
      full_nights: "6",
      wake_rested: "6",
      alcohol: "light",
      session_energy: "6",
      stress: "4",
      activity_load: "7",
      missed_sessions: "3",
    },
    expect: {
      min: 1,
      max: 3,
      mustInclude: ["no_surplus_no_growth"],
      mustExclude: ["gaining_too_fast", "fat_loss_without_deficit"],
      primaryOneOf: ["no_surplus_no_growth"],
    },
  },
  {
    name: "Veteran physique lifter who drinks and diets for muscle",
    track: "physique",
    answers: {
      training_age: "over_6y",
      training_pattern: "steady",
      physique_aim: "muscle",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lagging_area: "everything",
      lagging_priority: "middle",
      feel_target: "6",
      muscle_frequency: "twice",
      effort_grind: "7",
      beat_last: "7",
      range_under_load: "full",
      program_switch: "3",
      pain_limits: "2",
      eating_phase: "lose",
      appetite: "normal",
      meal_skip: "4",
      protein_meals: "7",
      weekend_eating: "4",
      full_nights: "6",
      wake_rested: "4",
      alcohol: "often",
      session_energy: "4",
      stress: "5",
      activity_load: "3",
      missed_sessions: "3",
    },
    expect: {
      min: 2,
      max: 4,
      mustInclude: ["deficit_while_expecting_muscle", "alcohol_tax"],
      // years of training must not turn a drinking, dieting lifter into "slow is normal"
      mustExclude: ["expecting_year_one_speed"],
      primaryOneOf: ["deficit_while_expecting_muscle", "alcohol_tax"],
    },
  },
  {
    name: "Physique dieter who does a lot of cardio and feels fine",
    track: "physique",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      physique_aim: "leaner",
      hard_set_habit: "push",
      volume_feel: "4",
      load_choice: "plan",
      lagging_area: "legs",
      lagging_priority: "middle",
      feel_target: "5",
      muscle_frequency: "once",
      effort_grind: "3",
      beat_last: "8",
      range_under_load: "unsure",
      program_switch: "3",
      pain_limits: "6",
      eating_phase: "lose",
      appetite: "normal",
      meal_skip: "7",
      protein_meals: "7",
      weekend_eating: "4",
      full_nights: "8",
      wake_rested: "7",
      alcohol: "light",
      session_energy: "8",
      stress: "4",
      activity_load: "8",
      missed_sessions: "3",
    },
    expect: {
      min: 0,
      max: 2,
      // deliberate cardio in a planned deficit, with energy and sleep intact, is not a recovery leak;
      // "Not sure" about range is not a shrinking range; "Wherever it fits" is not "trained last"
      mustExclude: ["cardio_eating_the_budget", "rom_shrinking", "lagging_part_trained_last", "fat_loss_without_deficit"],
    },
  },

  /* ───────────── strength ───────────── */
  {
    name: "Well-run strength lifter",
    track: "strength",
    answers: {
      training_age: "over_6y",
      training_pattern: "steady",
      main_lift: "squat",
      hard_set_habit: "push",
      volume_feel: "6",
      load_choice: "plan",
      lift_frequency: "twice",
      heavy_practice: "6",
      fail_point: "middle",
      weak_point_work: "7",
      form_breakdown: "3",
      effort_grind: "7",
      beat_last: "8",
      max_testing: "few_months",
      program_switch: "2",
      muscle_work: "6",
      pain_limits: "2",
      eating_phase: "maintain",
      meal_skip: "2",
      protein_meals: "8",
      full_nights: "8",
      wake_rested: "7",
      alcohol: "light",
      session_energy: "7",
      stress: "3",
      activity_load: "3",
      missed_sessions: "2",
    },
    expect: {
      min: 0,
      max: 2,
      primaryOneOf: ["expecting_year_one_speed"],
      mustExclude: ["testing_instead_of_training", "never_heavy_enough", "sticking_point_untrained", "no_forcing_function", "strength_without_muscle"],
    },
  },
  {
    name: "Typical stuck strength lifter",
    track: "strength",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      main_lift: "bench",
      hard_set_habit: "push",
      volume_feel: "4",
      load_choice: "feel",
      lift_frequency: "once",
      heavy_practice: "8",
      fail_point: "bottom",
      weak_point_work: "2",
      form_breakdown: "7",
      effort_grind: "6",
      beat_last: "5",
      max_testing: "monthly",
      program_switch: "4",
      muscle_work: "5",
      pain_limits: "3",
      eating_phase: "maintain",
      meal_skip: "5",
      protein_meals: "6",
      full_nights: "6",
      wake_rested: "6",
      alcohol: "light",
      session_energy: "6",
      stress: "5",
      activity_load: "3",
      missed_sessions: "3",
    },
    expect: {
      min: 3,
      max: 6,
      mustInclude: ["testing_instead_of_training", "main_lift_underpractised", "sticking_point_untrained"],
      mustExclude: ["never_heavy_enough", "volume_outruns_recovery", "sets_end_too_early", "consistency_gap"],
      primaryOneOf: ["testing_instead_of_training", "main_lift_underpractised"],
    },
  },
  {
    name: "Strength lifter running on empty",
    track: "strength",
    answers: {
      training_age: "3_6y",
      training_pattern: "steady",
      main_lift: "deadlift",
      hard_set_habit: "failure",
      volume_feel: "9",
      load_choice: "usual",
      lift_frequency: "twice",
      heavy_practice: "7",
      fail_point: "unsure",
      weak_point_work: "3",
      form_breakdown: "8",
      effort_grind: "10",
      beat_last: "3",
      max_testing: "few_months",
      program_switch: "5",
      muscle_work: "4",
      pain_limits: "7",
      eating_phase: "lose",
      meal_skip: "7",
      protein_meals: "6",
      full_nights: "3",
      wake_rested: "3",
      alcohol: "light",
      session_energy: "3",
      stress: "7",
      activity_load: "5",
      missed_sessions: "4",
    },
    expect: {
      min: 6,
      max: 10,
      mustInclude: ["failure_every_set", "volume_outruns_recovery", "strength_leaking_bodyweight", "sleep_under_dose", "form_breaks_under_load"],
      mustExclude: ["sets_end_too_early", "main_lift_underpractised", "never_heavy_enough", "restart_not_stall", "expecting_year_one_speed"],
      primaryOneOf: ["failure_every_set", "volume_outruns_recovery", "strength_leaking_bodyweight"],
    },
  },
  {
    name: "Strength lifter who keeps reps in reserve on purpose",
    track: "strength",
    answers: {
      training_age: "3_6y",
      training_pattern: "steady",
      main_lift: "bench",
      hard_set_habit: "stop",
      volume_feel: "6",
      load_choice: "plan",
      lift_frequency: "twice",
      heavy_practice: "6",
      fail_point: "bottom",
      weak_point_work: "6",
      form_breakdown: "3",
      effort_grind: "3",
      beat_last: "8",
      max_testing: "few_months",
      program_switch: "3",
      muscle_work: "6",
      pain_limits: "2",
      eating_phase: "maintain",
      meal_skip: "3",
      protein_meals: "7",
      full_nights: "7",
      wake_rested: "7",
      alcohol: "light",
      session_energy: "7",
      stress: "4",
      activity_load: "3",
      missed_sessions: "2",
    },
    expect: {
      min: 0,
      max: 2,
      // sets that stop short of a grind are sound strength practice when heavy work is in the week
      mustExclude: ["sets_end_too_early", "no_forcing_function"],
    },
  },
  {
    name: "Strength lifter with a big week who recovers fine",
    track: "strength",
    answers: {
      training_age: "1_3y",
      training_pattern: "steady",
      main_lift: "squat",
      hard_set_habit: "push",
      volume_feel: "8",
      load_choice: "plan",
      lift_frequency: "three",
      heavy_practice: "8",
      fail_point: "middle",
      weak_point_work: "6",
      form_breakdown: "3",
      effort_grind: "7",
      beat_last: "7",
      max_testing: "few_months",
      program_switch: "3",
      muscle_work: "5",
      pain_limits: "2",
      eating_phase: "maintain",
      meal_skip: "3",
      protein_meals: "7",
      full_nights: "7",
      wake_rested: "4",
      alcohol: "light",
      session_energy: "8",
      stress: "4",
      activity_load: "3",
      missed_sessions: "2",
    },
    expect: {
      min: 0,
      max: 2,
      // frequency and heavy work are not evidence of overreaching without a recovery symptom
      mustExclude: ["volume_outruns_recovery"],
    },
  },
  {
    name: "Strength lifter who changes programs now and then",
    track: "strength",
    answers: {
      training_age: "1_3y",
      training_pattern: "on_off",
      main_lift: "deadlift",
      hard_set_habit: "push",
      volume_feel: "5",
      load_choice: "feel",
      lift_frequency: "varies",
      heavy_practice: "5",
      fail_point: "top",
      weak_point_work: "5",
      form_breakdown: "4",
      effort_grind: "6",
      beat_last: "4",
      max_testing: "few_months",
      program_switch: "6",
      muscle_work: "5",
      pain_limits: "3",
      eating_phase: "maintain",
      meal_skip: "4",
      protein_meals: "6",
      full_nights: "6",
      wake_rested: "6",
      alcohol: "light",
      session_energy: "6",
      stress: "5",
      activity_load: "4",
      missed_sessions: "5",
    },
    expect: {
      min: 1,
      max: 3,
      mustInclude: ["no_forcing_function"],
      // a middling switch rate plus loose habits is a progression problem, not program hopping
      mustExclude: ["program_hopping"],
    },
  },
];
