/**
 * LiftDecode question bank (v2). Every question asks about a habit, a feeling
 * or an intensity, never a number or how progress is measured. QUESTIONS is the
 * display order; each track sees 28 (20 shared + 8 of its own). Sections only
 * group questions for ordering and are never shown.
 *
 * Answers that check each other sit far apart: training_pattern ↔ missed_sessions,
 * hard_set_habit ↔ effort_grind, load_choice ↔ beat_last, physique_aim ↔ eating_phase.
 * Answers that build on each other sit together: lagging_area → lagging_priority →
 * feel_target, and fail_point → weak_point_work.
 */
import type { Question, Section } from "./types";

const scale = (low: string, high: string) => ({ min: 1 as const, max: 10 as const, low, high });

export const SECTIONS: Section[] = [
  { id: "you", title: "You" },
  { id: "training", title: "Training" },
  { id: "food", title: "Food" },
  { id: "recovery", title: "Sleep and recovery" },
  { id: "life", title: "Life" },
];

export const QUESTIONS: Question[] = [
  /* ─────────────── you ─────────────── */
  {
    id: "goal",
    audience: "both",
    section: "you",
    type: "single",
    prompt: "What are you chasing right now?",
    options: [
      { value: "physique", label: "A better physique" },
      { value: "strength", label: "More strength" },
    ],
  },
  {
    id: "training_age",
    audience: "both",
    section: "you",
    type: "single",
    prompt: "How long have you trained seriously?",
    options: [
      { value: "under_1y", label: "Under a year" },
      { value: "1_3y", label: "1–3 years" },
      { value: "3_6y", label: "3–6 years" },
      { value: "over_6y", label: "Over 6 years" },
    ],
  },
  {
    id: "training_pattern",
    audience: "both",
    section: "you",
    type: "single",
    prompt: "Your last few months of training have been…",
    options: [
      { value: "steady", label: "Steady" },
      { value: "on_off", label: "On and off" },
      { value: "comeback", label: "Back after a break" },
    ],
  },
  {
    id: "physique_aim",
    audience: "physique",
    section: "you",
    type: "single",
    prompt: "What do you want most?",
    options: [
      { value: "muscle", label: "More muscle" },
      { value: "leaner", label: "Less fat" },
      { value: "both", label: "Both at once" },
    ],
  },
  {
    id: "main_lift",
    audience: "strength",
    section: "you",
    type: "single",
    prompt: "Which lift is most stuck?",
    options: [
      { value: "squat", label: "Squat" },
      { value: "bench", label: "Bench press" },
      { value: "deadlift", label: "Deadlift" },
      { value: "press", label: "Overhead press" },
    ],
  },

  /* ─────────────── training ─────────────── */
  {
    id: "hard_set_habit",
    audience: "both",
    section: "training",
    type: "single",
    prompt: "Most of your sets end…",
    options: [
      { value: "stop", label: "With plenty left" },
      { value: "push", label: "Just short of failure" },
      { value: "failure", label: "At failure" },
    ],
  },
  {
    id: "volume_feel",
    audience: "both",
    section: "training",
    type: "scale",
    prompt: "Compared with most lifters, how much do you train?",
    options: [],
    scale: scale("Far less", "Far more"),
  },
  {
    id: "load_choice",
    audience: "both",
    section: "training",
    type: "single",
    prompt: "How do you pick your weights?",
    options: [
      { value: "usual", label: "Same as usual" },
      { value: "feel", label: "By feel" },
      { value: "plan", label: "My program sets them" },
    ],
  },
  {
    id: "lift_frequency",
    audience: "strength",
    section: "training",
    type: "single",
    prompt: "How often do you train your stuck lift?",
    options: [
      { value: "once", label: "Once a week" },
      { value: "twice", label: "Twice a week" },
      { value: "three", label: "Three+ times" },
      { value: "varies", label: "Depends on the week" },
    ],
  },
  {
    id: "heavy_practice",
    audience: "strength",
    section: "training",
    type: "scale",
    prompt: "How often do you lift close to your max?",
    options: [],
    scale: scale("Almost never", "Every session"),
  },
  {
    id: "fail_point",
    audience: "strength",
    section: "training",
    type: "single",
    prompt: "Where do your heavy reps fail?",
    options: [
      { value: "bottom", label: "At the bottom" },
      { value: "middle", label: "Halfway up" },
      { value: "top", label: "Near lockout" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "weak_point_work",
    audience: "strength",
    section: "training",
    type: "scale",
    prompt: "How much of your work targets that weak spot?",
    options: [],
    scale: scale("None", "A lot"),
  },
  {
    id: "form_breakdown",
    audience: "strength",
    section: "training",
    type: "scale",
    prompt: "How much does your form change on heavy reps?",
    options: [],
    scale: scale("Not at all", "A lot"),
  },
  {
    id: "lagging_area",
    audience: "physique",
    section: "training",
    type: "single",
    prompt: "Which area is slowest to grow?",
    options: [
      { value: "chest_back", label: "Chest & back" },
      { value: "shoulders_arms", label: "Shoulders & arms" },
      { value: "legs", label: "Legs & glutes" },
      { value: "everything", label: "No one area" },
    ],
  },
  {
    id: "lagging_priority",
    audience: "physique",
    section: "training",
    type: "single",
    prompt: "When do you train what you most want to grow?",
    options: [
      { value: "first", label: "First, while fresh" },
      { value: "middle", label: "Wherever it fits" },
      { value: "last", label: "Last, when tired" },
      { value: "skipped", label: "Often skipped" },
    ],
  },
  {
    id: "feel_target",
    audience: "physique",
    section: "training",
    type: "scale",
    prompt: "How well do you feel the target muscle working?",
    options: [],
    scale: scale("Can't feel it", "Every rep"),
  },
  {
    id: "muscle_frequency",
    audience: "physique",
    section: "training",
    type: "single",
    prompt: "How often does each muscle get trained?",
    options: [
      { value: "once", label: "Once a week" },
      { value: "twice", label: "Twice a week" },
      { value: "three", label: "Three+ times" },
      { value: "varies", label: "Depends on the week" },
    ],
  },
  {
    id: "effort_grind",
    audience: "both",
    section: "training",
    type: "scale",
    prompt: "How often does your last rep slow to a grind?",
    options: [],
    scale: scale("Never", "Every set"),
  },
  {
    id: "beat_last",
    audience: "both",
    section: "training",
    type: "scale",
    prompt: "How often do you try to beat your last session?",
    options: [],
    scale: scale("Never", "Every session"),
  },
  {
    id: "range_under_load",
    audience: "physique",
    section: "training",
    type: "single",
    prompt: "As the weight goes up, your range of motion…",
    options: [
      { value: "full", label: "Stays full" },
      { value: "shorter", label: "Gets shorter" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "max_testing",
    audience: "strength",
    section: "training",
    type: "single",
    prompt: "How often do you test a max?",
    options: [
      { value: "never", label: "Almost never" },
      { value: "few_months", label: "Every few months" },
      { value: "monthly", label: "About monthly" },
      { value: "weekly", label: "Weekly or more" },
    ],
  },
  {
    id: "program_switch",
    audience: "both",
    section: "training",
    type: "scale",
    prompt: "How often do you start a new program?",
    options: [],
    scale: scale("Rarely", "Every few weeks"),
  },
  {
    id: "muscle_work",
    audience: "strength",
    section: "training",
    type: "scale",
    prompt: "How much accessory or bodybuilding work do you do?",
    options: [],
    scale: scale("None", "Loads"),
  },
  {
    id: "pain_limits",
    audience: "both",
    section: "training",
    type: "scale",
    prompt: "How often does pain change how you train?",
    options: [],
    scale: scale("Never", "Every session"),
  },

  /* ─────────────── food ─────────────── */
  {
    id: "eating_phase",
    audience: "both",
    section: "food",
    type: "single",
    prompt: "Right now, you're eating to…",
    options: [
      { value: "gain", label: "Gain weight" },
      { value: "lose", label: "Lose weight" },
      { value: "maintain", label: "Stay the same" },
      { value: "none", label: "No real plan" },
    ],
  },
  {
    id: "appetite",
    audience: "physique",
    section: "food",
    type: "single",
    prompt: "How is your appetite lately?",
    options: [
      { value: "small", label: "Hard to eat enough" },
      { value: "normal", label: "About right" },
      { value: "big", label: "Hard to keep in check" },
    ],
  },
  {
    id: "meal_skip",
    audience: "both",
    section: "food",
    type: "scale",
    prompt: "How often do you end up eating less than planned?",
    options: [],
    scale: scale("Never", "Every day"),
  },
  {
    id: "protein_meals",
    audience: "both",
    section: "food",
    type: "scale",
    prompt: "How often is a meal built around protein?",
    options: [],
    scale: scale("Hardly ever", "Every meal"),
  },
  {
    id: "weekend_eating",
    audience: "physique",
    section: "food",
    type: "scale",
    prompt: "How much looser is your weekend eating?",
    options: [],
    scale: scale("Not at all", "Anything goes"),
  },

  /* ─────────────── recovery ─────────────── */
  {
    id: "full_nights",
    audience: "both",
    section: "recovery",
    type: "scale",
    prompt: "How often do you get a full night's sleep?",
    options: [],
    scale: scale("Rarely", "Every night"),
  },
  {
    id: "wake_rested",
    audience: "both",
    section: "recovery",
    type: "scale",
    prompt: "How rested do you feel when you wake up?",
    options: [],
    scale: scale("Exhausted", "Fully rested"),
  },
  {
    id: "alcohol",
    audience: "both",
    section: "recovery",
    type: "single",
    prompt: "How much alcohol do you drink?",
    options: [
      { value: "none", label: "None" },
      { value: "light", label: "A little" },
      { value: "weekends", label: "Big weekends" },
      { value: "often", label: "Most days" },
    ],
  },
  {
    id: "session_energy",
    audience: "both",
    section: "recovery",
    type: "scale",
    prompt: "How much energy do you bring to your sessions?",
    options: [],
    scale: scale("Running on empty", "Fully charged"),
  },

  /* ─────────────── life ─────────────── */
  {
    id: "stress",
    audience: "both",
    section: "life",
    type: "scale",
    prompt: "How stressful is life right now?",
    options: [],
    scale: scale("Calm", "Overwhelming"),
  },
  {
    id: "activity_load",
    audience: "both",
    section: "life",
    type: "scale",
    prompt: "How much cardio, sport or physical work do you do?",
    options: [],
    scale: scale("None", "A lot"),
  },
  {
    id: "missed_sessions",
    audience: "both",
    section: "life",
    type: "scale",
    prompt: "How often do you miss a planned session?",
    options: [],
    scale: scale("Never", "All the time"),
  },
];
