// AUTO-GENERATED by scripts/gen-findings-index.mjs — do not edit by hand.
import type { FindingContent } from "../types";
import { FINDING as f0 } from "./alcohol_tax";
import { FINDING as f1 } from "./cardio_eating_the_budget";
import { FINDING as f2 } from "./consistency_gap";
import { FINDING as f3 } from "./deficit_while_expecting_muscle";
import { FINDING as f4 } from "./expecting_year_one_speed";
import { FINDING as f5 } from "./failure_every_set";
import { FINDING as f6 } from "./fat_loss_without_deficit";
import { FINDING as f7 } from "./form_breaks_under_load";
import { FINDING as f8 } from "./gaining_too_fast";
import { FINDING as f9 } from "./lagging_part_trained_last";
import { FINDING as f10 } from "./life_is_the_limiter";
import { FINDING as f11 } from "./main_lift_underpractised";
import { FINDING as f12 } from "./missed_dose";
import { FINDING as f13 } from "./never_heavy_enough";
import { FINDING as f14 } from "./no_forcing_function";
import { FINDING as f15 } from "./no_surplus_no_growth";
import { FINDING as f16 } from "./program_hopping";
import { FINDING as f17 } from "./protein_unknown";
import { FINDING as f18 } from "./recomp_window_closed";
import { FINDING as f19 } from "./restart_not_stall";
import { FINDING as f20 } from "./rom_shrinking";
import { FINDING as f21 } from "./sets_end_too_early";
import { FINDING as f22 } from "./sleep_under_dose";
import { FINDING as f23 } from "./sticking_point_untrained";
import { FINDING as f24 } from "./strength_leaking_bodyweight";
import { FINDING as f25 } from "./strength_without_muscle";
import { FINDING as f26 } from "./target_muscle_underdosed";
import { FINDING as f27 } from "./testing_instead_of_training";
import { FINDING as f28 } from "./training_around_pain";
import { FINDING as f29 } from "./volume_outruns_recovery";
import { FINDING as f30 } from "./week_cancels_itself";

export const FINDINGS: Record<string, FindingContent> = {
  ["alcohol_tax"]: f0,
  ["cardio_eating_the_budget"]: f1,
  ["consistency_gap"]: f2,
  ["deficit_while_expecting_muscle"]: f3,
  ["expecting_year_one_speed"]: f4,
  ["failure_every_set"]: f5,
  ["fat_loss_without_deficit"]: f6,
  ["form_breaks_under_load"]: f7,
  ["gaining_too_fast"]: f8,
  ["lagging_part_trained_last"]: f9,
  ["life_is_the_limiter"]: f10,
  ["main_lift_underpractised"]: f11,
  ["missed_dose"]: f12,
  ["never_heavy_enough"]: f13,
  ["no_forcing_function"]: f14,
  ["no_surplus_no_growth"]: f15,
  ["program_hopping"]: f16,
  ["protein_unknown"]: f17,
  ["recomp_window_closed"]: f18,
  ["restart_not_stall"]: f19,
  ["rom_shrinking"]: f20,
  ["sets_end_too_early"]: f21,
  ["sleep_under_dose"]: f22,
  ["sticking_point_untrained"]: f23,
  ["strength_leaking_bodyweight"]: f24,
  ["strength_without_muscle"]: f25,
  ["target_muscle_underdosed"]: f26,
  ["testing_instead_of_training"]: f27,
  ["training_around_pain"]: f28,
  ["volume_outruns_recovery"]: f29,
  ["week_cancels_itself"]: f30,
};

export const FINDING_LIST: FindingContent[] = Object.values(FINDINGS);
