/**
 * GENERATED by scripts/gen-evidence.mjs from the verified evidence base. Do not edit by hand.
 * 80 entries, each opened and checked against its source; the report model may cite
 * only these ids, and the report links each cited id to its source.
 */
export interface Evidence {
  id: string;
  section: string;
  claim: string;
  use: string;
  /** "Authors, year, journal" */
  source: string;
  url: string;
  /** strong | moderate | emerging, with the reason */
  confidence: string;
}

export const EVIDENCE: Evidence[] = [
  {
    "id": "CARDIO-01",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In human quadriceps, phosphocreatine (PCr) fell to 15–16% of its resting level after exhaustive exercise and was rebuilt in two phases: a fast phase with a half-time of 21–22 s and a slow phase with a half-time above 170 s. Occluding the leg's circulation completely abolished PCr resynthesis, which resumed only after the occlusion was released.",
    "use": "Explain that the \"refill\" between sets takes minutes, not seconds, and runs on blood flow, so the circulation that delivers oxygen sets how much of the next set's capacity comes back.",
    "source": "Harris RC, Edwards RH, Hultman E, et al., 1976, Pflügers Archiv",
    "url": "https://pubmed.ncbi.nlm.nih.gov/1034909/",
    "confidence": "strong (foundational biopsy finding; mechanism consistent with later work such as CARDIO-02)"
  },
  {
    "id": "CARDIO-02",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In six exercise-trained men doing 5 min of submaximal calf (plantar-flexion) exercise in an MR scanner, the PCr recovery time constant was 25.0 s breathing room air, 33.5 s breathing 10% oxygen and 20.0 s breathing 100% oxygen, with end-exercise pH not different. The authors conclude that PCr recovery under normal conditions is limited by oxygen availability.",
    "use": "The direct evidence that between-set recovery is an aerobic, oxygen-dependent process: more oxygen delivered to the muscle means a faster refill.",
    "source": "Haseler LJ, Hogan MC, Richardson RS, 1999, Journal of Applied Physiology",
    "url": "https://pubmed.ncbi.nlm.nih.gov/10368368/",
    "confidence": "moderate (clean manipulation, but n = 6 and small-muscle submaximal exercise)"
  },
  {
    "id": "CARDIO-03",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "Endurance-trained runners (n = 5, VO2max 66.2 ml/kg/min) resynthesised quadriceps PCr faster than untrained controls (n = 7, VO2max 52.0) at the same PCr level and muscle pH after knee-extension exercise, especially at higher intensities, and VO2max correlated negatively with the PCr recovery time constant across exercise intensities.",
    "use": "Supports telling a lifter that better aerobic fitness goes with faster PCr refill in the working muscle; present it as an association.",
    "source": "Takahashi H, Inaki M, Fujimoto K, et al., 1995, European Journal of Applied Physiology",
    "url": "https://pubmed.ncbi.nlm.nih.gov/8565970/",
    "confidence": "emerging (12 people, cross-sectional, correlation not causation)"
  },
  {
    "id": "CARDIO-04",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A review concluded that aerobic fitness enhances recovery from high-intensity intermittent exercise through a larger aerobic response, improved lactate removal and enhanced PCr regeneration; most studies found that endurance training or a higher VO2max gave better power recovery across repeated bouts. It also notes that PCr resynthesis after single high-intensity bouts does not always correlate with VO2max, and that the link is stronger for exercise using a large muscle mass.",
    "use": "Frame conditioning as a \"recover between efforts\" tool, while being clear that this evidence comes mainly from sprint-type intermittent exercise, not from lifting itself (see CARDIO-05 for the lifting-specific link).",
    "source": "Tomlin DL, Wenger HA, 2001, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/11219498/",
    "confidence": "moderate (narrative review of mixed findings)"
  },
  {
    "id": "CARDIO-05",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In 17 resistance-trained men doing 5 sets each of squat and bench press at 75% 1RM (up to 10 reps) with 1-, 2- or 3-min rests, total reps were highest with 3-min and lowest with 1-min rests, and oxygen uptake was highest with 1-min rests. VO2max correlated with the number of squat repetitions completed (r = 0.43–0.57) but not with bench press performance, and correlated negatively with squat and bench 1RM (r = −0.60 and −0.79); the authors conclude VO2max is related to lower-body resistance exercise performance when short rests are used.",
    "use": "The most lifting-specific link: a lifter with poor aerobic fitness is likely to lose squat reps when rests are short. The two fixes are more conditioning or longer rests; note that a higher VO2max did not go with a higher 1RM in this group.",
    "source": "Ratamess NA, Rosenberg JG, Kang J, et al., 2014, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24714546/",
    "confidence": "emerging (one cross-sectional correlation study, n = 17)"
  },
  {
    "id": "CARDIO-06",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In 22 resistance-trained men (28 ± 4 years) doing 5 sets of 10 squats at 65% 1RM with 3-min rests, mean heart rate rose from 156 bpm in set 1 to 175 bpm in set 5 (about 90% of measured maximal heart rate), and oxygen uptake reached 47.8 ml/kg/min in set 5, about 100.6% of their treadmill VO2max. The stronger half of the group reached a higher peak oxygen uptake relative to VO2max (108.0% vs 93.7%), and the authors state multiple squat sets can be considered vigorous-intensity cardiovascular activity.",
    "use": "The evidence that \"leg day is also a cardio stimulus\": hard multi-set squatting drives heart rate and oxygen demand to vigorous levels, so poor conditioning can cap how much productive leg volume a lifter can do.",
    "source": "Hong S, Oh M, Oh CG, et al., 2024, Scientific Reports",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11310470/",
    "confidence": "moderate (well-measured single lab study, one protocol, men only)"
  },
  {
    "id": "CARDIO-07",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In 15 men doing circuit weight lifting (bench press, bent-over row, arm curl and parallel squat; 10 reps in 30 s with 1:1 work-to-rest) at 40–70% 1RM, heart rate reached 63–82% of maximum while oxygen uptake was only 33–47% of VO2max. At any given %HRmax, %VO2max was consistently lower than predicted for running or cycling.",
    "use": "The counterweight to CARDIO-06: a high heart rate during lifting overstates its aerobic training effect, so lifting alone should not be described as a full substitute for conditioning.",
    "source": "Collins MA, Cureton KJ, Hill DW, Ray CA, 1991, Medicine and Science in Sports and Exercise",
    "url": "https://pubmed.ncbi.nlm.nih.gov/2072844/",
    "confidence": "moderate (older lab study; physiology consistent)"
  },
  {
    "id": "CARDIO-08",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In 22 healthy older men (71 ± 1 years) doing 24 weeks of progressive resistance training, type II fibre size increased overall (5,150 → 6,719 µm²), but the gain was driven by men with high baseline type II fibre capillarisation (5,170 → 7,133 µm²); the low-capillarisation group showed no significant change in fibre size or satellite-cell content. Resistance training did not change capillarisation in either group.",
    "use": "Explain that a muscle's capillary supply may set a ceiling on how much it can grow from lifting, and that lifting by itself did not build that supply here; present it as evidence from older men.",
    "source": "Snijders T, Nederveen JP, Joanisse S, et al., 2017, Journal of Cachexia, Sarcopenia and Muscle",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5377411/",
    "confidence": "emerging (older men only; retrospective high/low split of 22 people)"
  },
  {
    "id": "CARDIO-09",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "Fourteen healthy young men and women (22 ± 2 years) did 6 weeks of one-leg cycling and then 10 weeks of two-leg resistance training. The aerobically pre-conditioned leg increased type I, type II and mixed-fibre cross-sectional area, while the resistance-only leg only tended to increase type II area (p = .05). Higher capillarisation before resistance training was associated with larger fibre growth (type II r = 0.35), and the authors conclude aerobic conditioning before resistance training can augment its muscle adaptations.",
    "use": "Promising support for putting a short aerobic block before a hypertrophy block; say it is one small study.",
    "source": "Thomas ACQ, Brown A, Hatt AA, et al., 2022, FASEB Journal",
    "url": "https://pubmed.ncbi.nlm.nih.gov/35971745/",
    "confidence": "emerging (n = 14, single within-person study)"
  },
  {
    "id": "CARDIO-10",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A meta-analysis of 43 studies of healthy adults found that adding aerobic training to strength training did not compromise muscle hypertrophy (SMD −0.01) or maximal strength (SMD −0.06) but blunted explosive strength (SMD −0.28). The explosive-strength cost was larger when both were done in the same session than when sessions were at least 3 h apart. Cycling vs running, more vs fewer than 5 weekly sessions, training status and age (under vs over 40) did not change the results.",
    "use": "The headline reassurance: normal amounts of cardio do not erase muscle or maximal strength gains; explosive power is the quality to protect.",
    "source": "Schumann M, Feuerbacher JF, Sünkeler M, et al., 2022, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8891239/",
    "confidence": "strong (large meta-analysis; participants mostly untrained or moderately trained)"
  },
  {
    "id": "CARDIO-11",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A meta-analysis of 15 studies measuring muscle fibres found a small negative effect of concurrent training on overall fibre hypertrophy (SMD −0.23, 95% CI −0.46 to −0.00). Type I fibre growth was blunted when the aerobic training was running (SMD −0.81) but not cycling.",
    "use": "If muscle is the priority, steer most conditioning toward cycling, rowing or incline walking rather than lots of running.",
    "source": "Lundberg TR, Feuerbacher JF, Sünkeler M, Schumann M, 2022, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/35476184/",
    "confidence": "moderate (fibre-level data with a small effect; whole-muscle data in CARDIO-10 show no interference)"
  },
  {
    "id": "CARDIO-12",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "An earlier meta-analysis (21 studies, 422 effect sizes) found hypertrophy effect sizes of 1.23 for strength training alone vs 0.85 for concurrent training, and power effect sizes of 0.91 vs 0.55. Running, but not cycling, combined with strength training produced significant decrements in hypertrophy and strength, and the frequency (r −0.26 to −0.35) and duration (r −0.29 to −0.75) of endurance training correlated negatively with hypertrophy, strength and power gains.",
    "use": "Dose matters: longer and more frequent endurance sessions, especially running, are where interference shows up.",
    "source": "Wilson JM, Marin PJ, Rhea MR, et al., 2012, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/22002517/",
    "confidence": "moderate (older and smaller evidence base; its whole-muscle hypertrophy result was not replicated by CARDIO-10)"
  },
  {
    "id": "CARDIO-13",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A meta-analysis of 27 studies on lower-body 1RM found that concurrent training reduced leg press and squat strength gains in trained individuals (ES −0.35) but not in moderately trained (−0.20, p = 0.08) or untrained individuals (0.03). In trained individuals the cost appeared when endurance and resistance training were done in the same session (ES −0.66), not in separate sessions (−0.10, not significant).",
    "use": "For a trained strength-focused lifter, keep hard cardio out of the leg-strength session; separating them removes most of the measured cost.",
    "source": "Petré H, Hemmingsson E, Rosdahl H, Psilander N, 2021, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8053170/",
    "confidence": "moderate (meta-analysis; few studies in well-trained people)"
  },
  {
    "id": "CARDIO-14",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A meta-analysis of 59 studies (1,346 participants aged 18–50) found concurrent training blunted lower-body strength gains in males (SMD −0.43) but not in females (0.08). There were no sex differences for upper-body strength, power or VO2max, and hypertrophy data were insufficient to conclude.",
    "use": "Personalise by sex: men chasing lower-body strength have the most reason to manage cardio dose and timing.",
    "source": "Huiberts RO, Wüst RCI, van der Zwaard S, 2024, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10933151/",
    "confidence": "moderate (few studies in women and in highly trained athletes)"
  },
  {
    "id": "CARDIO-15",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A meta-analysis of 10 studies found that doing resistance exercise before endurance exercise in the same session gave a 6.91% larger gain in lower-body dynamic strength (95% CI 1.96–11.87) than the reverse order. Order had no effect on lower-body hypertrophy, static strength, VO2max or body-fat percentage.",
    "use": "If cardio and lifting must share a session, lift first.",
    "source": "Eddens L, van Someren K, Howatson G, 2018, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5752732/",
    "confidence": "moderate (10 studies, mostly recreational participants)"
  },
  {
    "id": "CARDIO-16",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "In 16 men, high-intensity interval or continuous submaximal aerobic exercise performed 4 h or 8 h before 4 sets of leg press and bench press at about 75% 1RM reduced total leg-press repetitions, while a 24-h gap did not differ from control. The type of aerobic exercise made no difference, and the impairment appeared localized to the muscle groups used in the aerobic exercise.",
    "use": "Hard leg-based cardio within roughly 8 hours before leg day costs reps; put it after lifting (see CARDIO-15) or on another day.",
    "source": "Sporer BC, Wenger HA, 2003, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/14636098/",
    "confidence": "moderate (acute study, n = 16)"
  },
  {
    "id": "CARDIO-17",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "A review with quantitative analysis found that full cardiac autonomic (parasympathetic) recovery after a single aerobic session takes up to 24 h after low-intensity exercise, 24–48 h after threshold-intensity exercise and at least 48 h after high-intensity exercise, and that it occurs more rapidly in individuals with greater aerobic fitness. Data after resistance exercise were limited.",
    "use": "Supports two points: fitter people's autonomic recovery returns faster between sessions, and hard interval sessions need at least about two days for full autonomic recovery, which competes with leg training. Say the data come from aerobic exercise.",
    "source": "Stanley J, Peake JM, Buchheit M, 2013, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23912805/",
    "confidence": "moderate for aerobic sessions; emerging as applied to lifting (resistance data limited)"
  },
  {
    "id": "CARDIO-18",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "The 2024 Adult Compendium of Physical Activities defines 1 MET as about 1.0 kcal/kg/h and lists measured values: running at 6–6.3 mph (10 min/mile) 9.3 METs; jogging, general 7.5 METs; stationary cycling, general 6.8 METs; stationary rowing, vigorous 7.3 METs; resistance training with multiple exercises at 8–15 reps 3.5 METs; and vigorous powerlifting or bodybuilding 6.0 METs.",
    "use": "Estimate the energy cost of the user's cardio as METs × body mass (kg) × hours. For example, an 80 kg lifter running 30 min at a 10-min-mile pace spends about 9.3 × 80 × 0.5 ≈ 370 kcal gross. Use this to check whether cardio is quietly erasing a planned surplus, and label it an estimate.",
    "source": "Herrmann SD, Willis EA, Ainsworth BE, et al., 2024, Journal of Sport and Health Science",
    "url": "https://doi.org/10.1016/j.jshs.2023.10.010",
    "confidence": "strong for ballpark estimates (measured values; individual cost varies)"
  },
  {
    "id": "CARDIO-19",
    "section": "CARDIO, CONDITIONING AND MUSCLE GROWTH",
    "claim": "CDC guidance says adults need 150 minutes of moderate-intensity physical activity a week, or 75 minutes of vigorous-intensity activity or an equivalent combination, plus at least 2 days of muscle-strengthening activity each week.",
    "use": "The health floor: right-size cardio rather than telling the user to drop it to zero.",
    "source": "Centers for Disease Control and Prevention, Adult Activity: An Overview (current page)",
    "url": "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
    "confidence": "strong (official public-health guideline)"
  },
  {
    "id": "SWEAT-01",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "Athletes' whole-body sweating rate typically ranges from about 0.5 to 2.0 L/h (above 3.0 L/h is rare, about 2% of athletes), local sweat sodium from about 10 to 90 mmol/L and whole-body sweat sodium from about 10 to 70 mmol/L. Sweat sodium rises as sweating rate rises (duct reabsorption is flow-dependent), heat acclimation lowers it, and dietary sodium changes it through aldosterone; aerobic training and heat acclimation make sweating start earlier and respond more strongly.",
    "use": "Explain why two lifters in the same session can lose very different amounts of salt, and that heavy, fast sweaters tend to lose saltier sweat.",
    "source": "Baker LB, 2017, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5371639/",
    "confidence": "strong (comprehensive review of measured data)"
  },
  {
    "id": "SWEAT-02",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "Recreationally active young adults with very salty sweat (sweat sodium 91.0 mmol/L) and controls with average sweat (43.7 mmol/L) cycled in the heat without drinking until 3% dehydration. The salty sweaters had a smaller rise in serum osmolality and a larger fall in plasma volume (−18.8% vs −14.3%), while thirst tracked dehydration similarly in both groups.",
    "use": "Shows that \"salty sweaters\" are a real, measurable group who lose more blood-plasma volume at the same level of dehydration. Use it to explain why salt replacement matters more for some people; do not use it to diagnose.",
    "source": "Brown MB, McCarty NA, Millard-Stafford M, 2011, American Journal of Physiology – Regulatory, Integrative and Comparative Physiology",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3197340/",
    "confidence": "emerging (small groups, heat with no drinking)"
  },
  {
    "id": "SWEAT-03",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "A meta-analysis of 28 papers found that hypohydration reduced muscle endurance by 8.3%, muscle strength by 5.5% and anaerobic power by 5.8%, while vertical jump was not impaired. The losses were smaller in trained individuals and when dehydration was induced passively rather than by exercise.",
    "use": "If the user sweats heavily and trains under-hydrated, expect a few percent less strength and noticeably fewer reps; hydration is a cheap fix to rule out.",
    "source": "Savoie FA, Kenefick RW, Ely BR, et al., 2015, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26178327/",
    "confidence": "moderate (meta-analysis of mixed dehydration methods)"
  },
  {
    "id": "SWEAT-04",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "The ACSM position stand says the goal of drinking during exercise is to prevent excessive dehydration (more than 2% body-weight loss from water deficit) and excessive changes in electrolyte balance. Because sweating rates and sweat electrolyte content vary considerably between individuals, it recommends customized fluid-replacement plans, notes that sweat rate can be estimated by weighing before and after exercise, and says drinks containing electrolytes and carbohydrate can benefit over water alone in certain circumstances.",
    "use": "Gives the user a concrete self-test: weigh before and after a typical session, accounting for fluid drunk, to see their sweat loss.",
    "source": "American College of Sports Medicine; Sawka MN, Burke LM, Eichner ER, et al., 2007, Medicine and Science in Sports and Exercise",
    "url": "https://pubmed.ncbi.nlm.nih.gov/17277604/",
    "confidence": "strong (official position stand)"
  },
  {
    "id": "SWEAT-05",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "The NATA position statement reports adult sweat rates of 0.5–4.0 L/h and sodium losses of 0.2–7.3 g/h during exercise, and recommends ending exercise with less than 2% body-mass loss without gaining weight. It defines exercise-associated hyponatraemia (EAH) as serum sodium below 135 mmol/L, reports it in 10–20% of distance athletes after events (uncommon in team sports), more often in women and after activity longer than 4 hours, and lists early signs: light-headedness, dizziness, nausea, puffiness of the hands or face, muscle cramps that do not resolve with usual care, and body-weight gain from baseline.",
    "use": "Safety guardrail: drinking large amounts of plain water beyond what is sweated out is the risk pattern. If the user describes symptoms like these, advise medical attention; never diagnose.",
    "source": "McDermott BP, Anderson SA, Armstrong LE, et al., 2017, Journal of Athletic Training (NATA position statement)",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5634236/",
    "confidence": "strong (official position statement)"
  },
  {
    "id": "SWEAT-06",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "Among 488 Boston Marathon runners who gave a finish-line blood sample, 13% had hyponatraemia (≤135 mmol/L) and 0.6% critical hyponatraemia (≤120 mmol/L). On multivariate analysis, risk was associated with weight gain during the race (odds ratio 4.2), a race time over 4 hours (odds ratio 7.4 vs under 3:30) and body-mass-index extremes; in univariate analysis, drinking more than 3 L during the race and drinking at every mile were also associated.",
    "use": "Shows that overdrinking (gaining weight while exercising) drives low blood sodium; relevant when a user forces large volumes of plain water. It is marathon data, so describe it as such.",
    "source": "Almond CS, Shin AY, Fortescue EB, et al., 2005, New England Journal of Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/15829535/",
    "confidence": "strong for marathoners; indirect for gym sessions"
  },
  {
    "id": "SWEAT-07",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "An evidence-based review concluded that exercise-associated muscle cramps arise from a confluence of intrinsic and extrinsic factors rather than a single cause. Acute treatment is gentle static stretching, and prevention should target the individual's own risk factors rather than generalized advice such as drinking more fluids.",
    "use": "Frame cramps as multifactorial (fatigue, intensity, history, fluid and salt) and avoid promising that salt alone fixes them.",
    "source": "Miller KC, McDermott BP, Yeargin SW, Fiol A, Schwellnus MP, 2022, Journal of Athletic Training",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8775277/",
    "confidence": "moderate (review of conflicting evidence)"
  },
  {
    "id": "SWEAT-08",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "In a prospective study of 210 Ironman triathletes, the 43 who cramped did not differ from non-crampers in pre-to-post-race serum electrolytes or body-weight change. Faster race times and a history of cramping in the last 10 races were the only independent risk factors.",
    "use": "Counterweight to the salt story: cramps often track intensity, fatigue and personal history rather than measurable dehydration.",
    "source": "Schwellnus MP, Drew N, Collins M, 2011, British Journal of Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/21148567/",
    "confidence": "moderate (prospective cohort in an endurance setting)"
  },
  {
    "id": "SWEAT-09",
    "section": "SWEAT, SODIUM AND ELECTROLYTES",
    "claim": "Ten men ran downhill in the heat until they lost about 2% of body mass, then drank either plain spring water or an oral rehydration solution. After plain water, the electrical stimulation frequency needed to provoke a cramp fell by 4.3 Hz at 30 min and 5.1 Hz at 60 min (muscles became more cramp-prone) and serum sodium and chloride fell; after the electrolyte drink the threshold rose by 3.7 and 5.4 Hz and electrolytes were maintained. A 2019 correction changed only the stated composition of the electrolyte drink.",
    "use": "The closest evidence behind \"worse after chugging plain water\": after a heavy sweat, replacing losses with an electrolyte drink rather than plain water is a reasonable, low-risk experiment. It measured cramp susceptibility, not strength.",
    "source": "Lau WY, Kato H, Nosaka K, 2019, BMJ Open Sport & Exercise Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6407543/",
    "confidence": "emerging (n = 10, electrically induced cramps)"
  },
  {
    "id": "CARB-01",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "In 8 bodybuilders doing a typical arm-curl session at 80% 1RM, biceps PCr fell 62% and glycogen 12% after 1 set, and PCr fell 50% and glycogen 24% after 3 sets (n = 4 per time point).",
    "use": "A normal hypertrophy session draws on muscle glycogen, about a quarter of the working muscle's store after 3 sets in this study, so fuelling matters more as volume per muscle climbs.",
    "source": "MacDougall JD, Ray S, Sale DG, et al., 1999, Canadian Journal of Applied Physiology",
    "url": "https://pubmed.ncbi.nlm.nih.gov/10364416/",
    "confidence": "emerging (very small samples, one exercise)"
  },
  {
    "id": "CARB-02",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "In 9 strength-trained athletes doing 5 sets each of front squats, back squats, leg presses and knee extensions to failure (6–12 reps per set, about 30 minutes), thigh (vastus lateralis) glycogen fell from 160 to 118 mmol/kg wet weight, alongside significant drops in ATP and creatine phosphate.",
    "use": "A high-volume leg day uses a meaningful but partial share of thigh glycogen (roughly a quarter, calculated from the reported values), so carbohydrate matters most for big leg sessions and for training on consecutive days.",
    "source": "Tesch PA, Colliander EB, Kaiser P, 1986, European Journal of Applied Physiology",
    "url": "https://pubmed.ncbi.nlm.nih.gov/3758035/",
    "confidence": "moderate (classic biopsy data, n = 9)"
  },
  {
    "id": "CARB-03",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "A review notes that current literature suggests a moderately high carbohydrate intake (3–7 g/kg/day) for resistance training, but argues that true glycogen depletion from resistance exercise is unlikely, that a carbohydrate-restricted diet may not harm acute resistance-exercise performance or the cell signalling for adaptation, and that mTORC1 signalling appears unaffected by carbohydrate restriction or low glycogen.",
    "use": "Prevents over-claiming: low carbohydrate is rarely the first limiter for a typical lifter unless volume is high or total intake is very low.",
    "source": "Escobar KA, VanDusseldorp TA, Kerksick CM, 2016, British Journal of Nutrition",
    "url": "https://pubmed.ncbi.nlm.nih.gov/27993175/",
    "confidence": "moderate (narrative review)"
  },
  {
    "id": "CARB-04",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "A systematic review of 49 studies found that, acutely, more carbohydrate did not improve strength-training performance in 13 studies and improved it in 6, mainly against fasted controls and in workouts of more than 10 sets per muscle group. None of 7 short-term (2–7 day) studies found a benefit, and longer-term strength changes were not influenced by carbohydrate intake in 15 of 17 studies. The authors conclude that carbohydrate intake per se is unlikely to affect strength-training performance in a fed state for workouts of up to 10 sets per muscle group.",
    "use": "Flag carbohydrate as a likely issue only when the user trains fasted, runs very high-volume sessions (more than about 10 sets for one muscle) or trains twice a day.",
    "source": "Henselmans M, Bjørnsen T, Hedderman R, Vårvik FT, 2022, Nutrients",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8878406/",
    "confidence": "moderate (systematic review of heterogeneous studies)"
  },
  {
    "id": "CARB-05",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "The ISSN nutrient-timing position stand says glycogen stores are maximized by a high-carbohydrate diet (8–12 g/kg/day) and depleted most by high-volume exercise. For rapid restoration in under 4 h it suggests 1.2 g/kg/h of carbohydrate, or 0.8 g/kg/h carbohydrate with 0.2–0.4 g/kg/h protein, and it states that carbohydrate taken during resistance exercise (e.g., 3–6 sets of 8–12RM across major muscle groups) promotes stable blood glucose and higher glycogen stores.",
    "use": "Numbers for the unusual case (two sessions a day, or very long sessions); a typical 45–60 minute session does not need them.",
    "source": "Kerksick CM, Arent S, Schoenfeld BJ, et al., 2017, Journal of the International Society of Sports Nutrition",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5596471/",
    "confidence": "moderate (position stand; the 8–12 g/kg figure comes from endurance contexts)"
  },
  {
    "id": "CARB-06",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "For natural bodybuilders in the off-season, this review recommends a caloric surplus of about 10–20% targeting a weight gain of about 0.25–0.5% of bodyweight per week for novices and intermediates (more conservative for advanced lifters); protein at 1.6–2.2 g/kg/day in 0.40–0.55 g/kg meals over 3–6 meals; fat at 0.5–1.5 g/kg/day; and the remaining calories from carbohydrate, with at least 3–5 g/kg/day to support resistance-training energy demands.",
    "use": "A defensible carbohydrate floor and a rate-of-gain target for physique-track users in a growth phase (also relevant to gaining-too-fast and no-surplus findings).",
    "source": "Iraki J, Fitschen P, Espinar S, Helms E, 2019, Sports (Basel)",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6680710/",
    "confidence": "moderate (narrative review; expert recommendations)"
  },
  {
    "id": "CARB-07",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "In 16 resistance-trained men who habitually ate breakfast, skipping breakfast (water only) instead of eating a meal with 1.5 g/kg carbohydrate 2 h before training reduced total reps across 4 sets to failure at 90% of 10RM: back squat 58 vs 68 reps and bench press 38 vs 40 reps.",
    "use": "If the user trains in the morning without eating, a carbohydrate-containing meal about 2 hours before is a cheap experiment that may add reps.",
    "source": "Bin Naharudin MN, Yusof A, Shaw H, et al., 2019, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/30707135/",
    "confidence": "emerging (single crossover study, habitual breakfast eaters only, no placebo meal)"
  },
  {
    "id": "CARB-08",
    "section": "CARBOHYDRATE AND GLYCOGEN",
    "claim": "A review of pre-exercise carbohydrate feeding found that carbohydrate eaten 30–60 min before exercise can cause rebound hypoglycaemia in some people, yet almost all studies show unaltered or improved performance, so advice to avoid carbohydrate in the hour before exercise is unfounded. Some athletes report symptoms resembling hypoglycaemia that are rarely linked to actually low blood glucose, which calls for an individual approach.",
    "use": "If a user feels shaky or foggy after a pre-workout snack, suggest adjusting its timing and size; do not label it low blood sugar.",
    "source": "Jeukendrup AE, Killer SC, 2010, Annals of Nutrition and Metabolism",
    "url": "https://pubmed.ncbi.nlm.nih.gov/21346333/",
    "confidence": "moderate (review; mostly endurance exercise studies)"
  },
  {
    "id": "SLEEP-01",
    "section": "SLEEP",
    "claim": "The American Academy of Sleep Medicine and Sleep Research Society consensus says adults should sleep 7 or more hours per night on a regular basis. Regularly sleeping less than 7 hours is associated with adverse health outcomes and with impaired performance, more errors and greater accident risk, and more than 9 hours may be appropriate for young adults, people recovering from sleep debt and people who are ill. The statement applies to adults aged 18 to 60.",
    "use": "The baseline sleep target for adult users.",
    "source": "Watson NF, Badr MS, Belenky G, et al., 2015, Sleep (joint AASM/SRS consensus)",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4434546/",
    "confidence": "strong (expert consensus of the main US sleep bodies)"
  },
  {
    "id": "SLEEP-02",
    "section": "SLEEP",
    "claim": "The National Sleep Foundation's expert panel recommends 8–10 hours for teenagers, 7–9 hours for young adults and adults, and 7–8 hours for older adults, noting that needs vary across the lifespan and between people.",
    "use": "Age-specific targets for teenage and older users.",
    "source": "Hirshkowitz M, Whiton K, Albert SM, et al., 2015, Sleep Health",
    "url": "https://pubmed.ncbi.nlm.nih.gov/29073412/",
    "confidence": "strong (expert consensus)"
  },
  {
    "id": "SLEEP-03",
    "section": "SLEEP",
    "claim": "In 13 healthy young adults (7 men, 6 women) in a randomized crossover, one night of total sleep deprivation reduced postprandial muscle protein synthesis by 18%, raised plasma cortisol by 21% and lowered plasma testosterone by 24% the following day; markers of protein breakdown did not change.",
    "use": "Mechanism: even one sleepless night blunts the muscle-building response to meals.",
    "source": "Lamon S, Morabito A, Arentson-Lantz E, et al., 2021, Physiological Reports",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7785053/",
    "confidence": "emerging (acute, small sample, total deprivation rather than short sleep)"
  },
  {
    "id": "SLEEP-04",
    "section": "SLEEP",
    "claim": "In 24 healthy young men, five nights with 4 h in bed lowered myofibrillar protein synthesis to 1.24%/day, versus 1.53%/day with 8 h in bed; a group that had the same restricted sleep but did three high-intensity interval sessions maintained it (1.61%/day).",
    "use": "Repeated short nights lower the muscle-building rate itself; training partly offsets this, but sleep is the cheaper fix.",
    "source": "Saner NJ, Lee MJ, Pitchford NW, et al., 2020, Journal of Physiology",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7217042/",
    "confidence": "emerging (5 days, men only, synthesis rate as a proxy for growth)"
  },
  {
    "id": "SLEEP-05",
    "section": "SLEEP",
    "claim": "A meta-analysis of 69 publications (227 outcomes; 89% male participants) found that sleep loss (6 h or less in 24 h) reduced exercise performance by 7.56% on average, with significant effects in every category including strength. Consistent effects appeared for total deprivation and for late restriction (waking earlier than normal); performance fell about 0.4% for every extra hour awake before exercise, and tasks performed in the afternoon or evening were affected while morning tasks were largely not.",
    "use": "A short night costs performance, particularly for evening sessions; if a short night is unavoidable, training earlier in the day limits the cost.",
    "source": "Craven J, McCartney D, Desbrow B, et al., 2022, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9584849/",
    "confidence": "moderate (large meta-analysis but very high heterogeneity, I² = 98.1%)"
  },
  {
    "id": "SLEEP-06",
    "section": "SLEEP",
    "claim": "Ten overweight adults on 14 days of moderate calorie restriction lost 55% less of their weight as fat with 5.5 h of nightly sleep opportunity than with 8.5 h (0.6 vs 1.4 kg fat), and lost 60% more fat-free mass (2.4 vs 1.5 kg).",
    "use": "Dieting on short sleep shifts the losses from fat toward lean mass, which matters most for users in a deficit.",
    "source": "Nedeltcheva AV, Kilkus JM, Imperial J, et al., 2010, Annals of Internal Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC2951287/",
    "confidence": "emerging (n = 10, 2-week crossover, non-lifters)"
  },
  {
    "id": "SLEEP-07",
    "section": "SLEEP",
    "claim": "A National Sleep Foundation expert panel that reviewed 63 publications reached consensus that daily regularity in sleep timing is important for both health and performance, and that when weekday sleep is insufficient, weekend catch-up sleep may be beneficial.",
    "use": "Supports the sleep-timing finding: consistent bed and wake times matter, not just total hours.",
    "source": "Sletten TL, Weaver MD, Foster RG, et al., 2023, Sleep Health",
    "url": "https://pubmed.ncbi.nlm.nih.gov/37684151/",
    "confidence": "moderate (expert consensus; not specific to lifting outcomes)"
  },
  {
    "id": "SLEEP-08",
    "section": "SLEEP",
    "claim": "HYPOTHESIS (no new data): the authors propose that sleep debt, through higher cortisol and lower testosterone and IGF-1, reduces the activity of protein-synthesis pathways and increases degradation pathways, favouring muscle loss and hindering recovery from exercise-induced muscle damage.",
    "use": "Only as the theoretical frame, always labelled a hypothesis; cite SLEEP-03 and SLEEP-04 for actual measurements.",
    "source": "Dattilo M, Antunes HK, Medeiros A, et al., 2011, Medical Hypotheses",
    "url": "https://pubmed.ncbi.nlm.nih.gov/21550729/",
    "confidence": "emerging (hypothesis paper)"
  },
  {
    "id": "CAFF-01",
    "section": "CAFFEINE",
    "claim": "The ISSN position stand says caffeine consistently improves exercise performance at 3–6 mg/kg body mass, the minimal effective dose may be as low as 2 mg/kg, and very high doses (e.g., 9 mg/kg) bring a high incidence of side-effects without being needed for an ergogenic effect. The most common timing is 60 min before exercise; benefits include small-to-moderate gains in muscular endurance, movement velocity and strength, and individual differences in effects on sleep and anxiety may be attributed to genetic variation, with habitual intake also possibly playing a role.",
    "use": "Right-size the pre-workout: about 3 mg/kg is usually enough and keeps daily totals within CAFF-04 (e.g., 3 mg/kg for an 80 kg lifter is about 240 mg).",
    "source": "Guest NS, VanDusseldorp TA, Nelson MT, et al., 2021, Journal of the International Society of Sports Nutrition",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7777221/",
    "confidence": "strong (position stand built on many trials)"
  },
  {
    "id": "CAFF-02",
    "section": "CAFFEINE",
    "claim": "In 12 healthy adults given 400 mg caffeine 0, 3 or 6 h before habitual bedtime, objectively measured total sleep time fell by 1.1–1.2 h at every timing, including 6 h before bed; self-reported (diary) sleep fell by 41 min with the 6-h dose (p = 0.08).",
    "use": "A large pre-workout dose even 6 hours before bed can cost about an hour of sleep, often without the user noticing it.",
    "source": "Drake C, Roehrs T, Shambroom J, Roth T, 2013, Journal of Clinical Sleep Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3805807/",
    "confidence": "moderate (small randomized crossover with a home sleep monitor)"
  },
  {
    "id": "CAFF-03",
    "section": "CAFFEINE",
    "claim": "A meta-analysis of 24 studies found caffeine reduced total sleep time by 45 min and sleep efficiency by 7%, lengthened time to fall asleep by 9 min and time awake after sleep onset by 12 min, and reduced deep sleep by 11.4 min. To avoid losing sleep time, the authors advise taking coffee (107 mg per 250 mL) at least 8.8 h before bedtime and a standard pre-workout serving (217.5 mg) at least 13.2 h before bedtime.",
    "use": "Concrete cut-off times; the classic case is an evening lifter using pre-workout.",
    "source": "Gardiner C, Weakley J, Burke LM, et al., 2023, Sleep Medicine Reviews",
    "url": "https://doi.org/10.1016/j.smrv.2023.101764",
    "confidence": "strong (recent meta-analysis with dose and timing analysis)"
  },
  {
    "id": "CAFF-04",
    "section": "CAFFEINE",
    "claim": "The FDA says that for most adults 400 mg of caffeine a day (about two to three 12-fl-oz cups of coffee) is not generally associated with negative effects, that sensitivity and elimination speed vary widely, and that too much caffeine can cause increased heart rate, palpitations, high blood pressure, insomnia or sleep disruption, anxiety, jitters, upset stomach, nausea and headache; toxic effects such as seizures can occur with rapid intake of about 1,200 mg.",
    "use": "The daily ceiling plus a symptom checklist for the caffeine-overload finding; for persistent symptoms like palpitations, advise talking to a doctor.",
    "source": "U.S. Food and Drug Administration, \"Spilling the Beans: How Much Caffeine Is Too Much?\"",
    "url": "https://www.fda.gov/consumers/consumer-updates/spilling-beans-how-much-caffeine-too-much",
    "confidence": "strong (regulator guidance)"
  },
  {
    "id": "ALC-01",
    "section": "ALCOHOL",
    "claim": "In 8 physically active men, drinking 1.5 g/kg alcohol (about 12 ± 2 standard drinks) after a session of leg resistance exercise plus cycling reduced myofibrillar protein synthesis by 24% when taken with 25 g protein and by 37% when taken with carbohydrate, compared with protein alone; synthesis still rose above resting levels in every condition.",
    "use": "Heavy drinking after training blunts the muscle-building response even with a protein shake; the study used a binge-level dose.",
    "source": "Parr EB, Camera DM, Areta JL, et al., 2014, PLoS One",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3922864/",
    "confidence": "moderate (well-controlled crossover, but n = 8 and a very high dose)"
  },
  {
    "id": "ALC-02",
    "section": "ALCOHOL",
    "claim": "Eleven healthy men performed 300 maximal eccentric quadriceps contractions and then drank 1 g/kg alcohol or an isocaloric orange juice. At 36 h, isometric, concentric and eccentric strength losses were 34%, 40% and 34% after alcohol versus 12%, 28% and 19% after juice, with no difference in creatine kinase or soreness.",
    "use": "After a damaging leg session, a night of drinking can deepen the strength dip over the next day or two.",
    "source": "Barnes MJ, Mündel T, Stannard SR, 2010, Journal of Science and Medicine in Sport",
    "url": "https://pubmed.ncbi.nlm.nih.gov/19230764/",
    "confidence": "emerging (n = 11, extreme eccentric protocol)"
  },
  {
    "id": "ALC-03",
    "section": "ALCOHOL",
    "claim": "A systematic review of 12 studies found that alcohol consumed after resistance exercise did not appear to change force, power, muscular endurance, soreness or perceived exertion during recovery, nor creatine kinase, heart rate, lactate or C-reactive protein; cortisol rose while testosterone, plasma amino acids and muscle protein synthesis fell.",
    "use": "Honest counterweight: one evening's drinking usually does not wreck the next session's performance; the cost shows up in the anabolic response and recovery quality.",
    "source": "Lakićević N, 2019, Journal of Functional Morphology and Kinesiology",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7739274/",
    "confidence": "moderate (small literature, mixed doses)"
  },
  {
    "id": "ALC-04",
    "section": "ALCOHOL",
    "claim": "In a real-world sample of 4,098 Finnish employees, alcohol was dose-dependently associated with lower heart-rate-variability-derived physiological recovery during the first 3 h of sleep: −9.3, −24.0 and −39.2 percentage units for low (≤0.25 g/kg), moderate (>0.25–0.75 g/kg) and high (>0.75 g/kg) intake. The effects were similar in physically active and sedentary people.",
    "use": "Even low intake measurably dents overnight recovery markers (for an 80 kg person, 0.25 g/kg is 20 g of alcohol).",
    "source": "Pietilä J, Helander E, Korhonen I, et al., 2018, JMIR Mental Health",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5878366/",
    "confidence": "moderate (large but observational; self-reported intake; HRV is a proxy)"
  },
  {
    "id": "PROT-01",
    "section": "PROTEIN",
    "claim": "A meta-analysis of 49 randomized trials (1,863 participants) found protein supplementation during at least 6 weeks of resistance training increased 1RM by 2.49 kg and fat-free mass by 0.30 kg. The effect shrank with age and was larger in resistance-trained people (0.75 kg). Fat-free-mass gains plateaued at a total intake of 1.62 g/kg/day (95% CI 1.03–2.20; the break-point itself was not statistically significant, p = 0.079), and the authors suggest about 2.2 g/kg/day may be prudent for those seeking to maximize gains.",
    "use": "Primary target of at least 1.6 g/kg/day, up to about 2.2 g/kg/day for users who want a safety margin.",
    "source": "Morton RW, Murphy KT, McKellar SR, et al., 2018, British Journal of Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5867436/",
    "confidence": "strong (largest meta-analysis on the question)"
  },
  {
    "id": "PROT-02",
    "section": "PROTEIN",
    "claim": "The ISSN position stand says 1.4–2.0 g/kg/day is sufficient for most exercising individuals, 2.3–3.1 g/kg/day may be needed to maximize lean-mass retention in resistance-trained people during calorie deficits, and per-serving targets are 0.25 g/kg or 20–40 g of high-quality protein containing 700–3,000 mg leucine, evenly distributed every 3–4 h. It adds that 30–40 g of casein before sleep increases overnight muscle protein synthesis.",
    "use": "Per-meal targets and the higher range for users who are cutting.",
    "source": "Jäger R, Kerksick CM, Campbell BI, et al., 2017, Journal of the International Society of Sports Nutrition",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/",
    "confidence": "strong (position stand)"
  },
  {
    "id": "PROT-03",
    "section": "PROTEIN",
    "claim": "This review found that protein doses above 20 g increase amino-acid oxidation but that not all of the extra amino acids are oxidized; some are used for tissue building. To maximize anabolism it recommends 0.4 g/kg per meal across at least four meals to reach at least 1.6 g/kg/day, and up to 0.55 g/kg per meal for an intake of 2.2 g/kg/day.",
    "use": "A concrete meal template (e.g., four meals of 0.4 g/kg).",
    "source": "Schoenfeld BJ, Aragon AA, 2018, Journal of the International Society of Sports Nutrition",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5828430/",
    "confidence": "moderate (narrative review)"
  },
  {
    "id": "PROT-04",
    "section": "PROTEIN",
    "claim": "In 24 healthy trained men who ate 80 g whey protein over 12 h after resistance exercise, 4 × 20 g every 3 h produced greater myofibrillar protein synthesis (31–48% higher) than 8 × 10 g every 1.5 h or 2 × 40 g every 6 h.",
    "use": "Supports building about 20 g or more of protein into each of several meals rather than one or two large feeds or constant grazing.",
    "source": "Areta JL, Burke LM, Ross ML, et al., 2013, Journal of Physiology",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23459753/",
    "confidence": "moderate (acute 12-hour study; total daily intake matters more than pattern)"
  },
  {
    "id": "PROT-05",
    "section": "PROTEIN",
    "claim": "In 36 healthy, recreationally active young men, ingesting 100 g protein after whole-body resistance exercise produced a greater and more prolonged (more than 12 h) anabolic response than 25 g, with a negligible effect on amino-acid oxidation.",
    "use": "A large protein meal is not \"wasted\": total daily protein comes first and distribution is a refinement. Use this with PROT-04 to avoid dogma about per-meal limits.",
    "source": "Trommelen J, van Lieshout GAA, Nyakayiru J, et al., 2023, Cell Reports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10772463/",
    "confidence": "moderate (rigorous acute tracer study; young men only)"
  },
  {
    "id": "PROT-06",
    "section": "PROTEIN",
    "claim": "In 40 young men on a 4-week diet about 40% below energy needs while doing resistance training plus high-intensity intervals 6 days a week, 2.4 g/kg/day protein produced a lean-mass gain of 1.2 kg and a fat loss of 4.8 kg, versus 0.1 kg lean gain and 3.5 kg fat loss on 1.2 g/kg/day.",
    "use": "When cutting, higher protein protects lean mass and can even support small gains.",
    "source": "Longland TM, Oikawa SY, Mitchell CJ, Devries MC, Phillips SM, 2016, American Journal of Clinical Nutrition",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26817506/",
    "confidence": "moderate (randomized trial, short and aggressive deficit)"
  },
  {
    "id": "TRAIN-01",
    "section": "TRAINING STIMULUS",
    "claim": "A meta-regression of 15 studies (34 treatment groups) found a graded dose-response between weekly sets and muscle growth: each additional weekly set was associated with about 0.37% more gain, higher versus lower volume within studies differed by 3.9%, and a comparison of fewer than 5, 5–9 and 10 or more sets per muscle per week showed a trend (p = 0.074).",
    "use": "More hard weekly sets for a lagging muscle is the first lever, within what the user can recover from.",
    "source": "Schoenfeld BJ, Ogborn D, Krieger JW, 2017, Journal of Sports Sciences",
    "url": "https://pubmed.ncbi.nlm.nih.gov/27433992/",
    "confidence": "moderate (meta-regression of 15 studies; updated by TRAIN-02)"
  },
  {
    "id": "TRAIN-02",
    "section": "TRAINING STIMULUS",
    "claim": "Meta-regressions of 67 studies (2,058 participants) found that muscle size and strength both increase as weekly set volume increases, with diminishing returns that are much more pronounced for strength. Counting indirect sets as half a set (\"fractional\" method) fitted the data best. Frequency had negligible effect on hypertrophy, while strength gains increased with frequency, again with diminishing returns.",
    "use": "Count weekly sets per muscle (indirect work as 0.5); more volume keeps paying for size, while strength users get more from frequency and practice than from piling on sets.",
    "source": "Pelland JC, Remmert JF, Robinson ZP, Hinson SR, Zourdos MC, 2026, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/41343037/",
    "confidence": "strong (largest dose-response analysis to date)"
  },
  {
    "id": "TRAIN-03",
    "section": "TRAINING STIMULUS",
    "claim": "A meta-analysis of 10 studies found that training a muscle group twice a week produced greater hypertrophy than once a week on a volume-equated basis (effect size 0.49 vs 0.30), and concluded major muscles should be trained at least twice a week; whether three times beats two was undetermined.",
    "use": "A muscle hit once a week is a fixable bottleneck: split the same sets over two sessions.",
    "source": "Schoenfeld BJ, Ogborn D, Krieger JW, 2016, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/27102172/",
    "confidence": "moderate (10 studies; TRAIN-02 suggests frequency matters mainly as a way to distribute volume)"
  },
  {
    "id": "TRAIN-04",
    "section": "TRAINING STIMULUS",
    "claim": "Exploratory meta-regressions found that muscle hypertrophy increased as sets were terminated closer to failure (fewer repetitions in reserve), while strength gains were similar across a wide range of repetitions in reserve; the authors caution that RIR was estimated from study descriptions.",
    "use": "For size, sets need to finish genuinely close to failure; for strength, effort per set matters less than load and practice.",
    "source": "Robinson ZP, Pelland JC, Remmert JF, et al., 2024, Sports Medicine",
    "url": "https://pubmed.ncbi.nlm.nih.gov/38970765/",
    "confidence": "moderate (exploratory analysis with estimated RIR)"
  },
  {
    "id": "TRAIN-05",
    "section": "TRAINING STIMULUS",
    "claim": "A meta-analysis of 15 studies found a trivial advantage for training to set failure versus non-failure when any definition of failure was used (ES 0.19), but no advantage for momentary muscular failure versus non-failure (ES 0.12, not significant), suggesting a non-linear relationship between proximity to failure and hypertrophy.",
    "use": "Hard sets are needed, but going to absolute failure on every set is not; stopping a little short of failure on most sets is defensible.",
    "source": "Refalo MC, Helms ER, Trexler ET, Hamilton DL, Fyfe JJ, 2023, Sports Medicine",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9935748/",
    "confidence": "moderate (meta-analysis; varied definitions of failure)"
  },
  {
    "id": "TRAIN-06",
    "section": "TRAINING STIMULUS",
    "claim": "A meta-analysis of 21 studies in which all sets went to momentary failure found greater 1RM strength gains with high loads (above 60% 1RM) than low loads (60% or less), while hypertrophy was similar between conditions.",
    "use": "Size can be built across a wide rep range if sets are hard, but maximal strength needs heavy loads.",
    "source": "Schoenfeld BJ, Grgic J, Ogborn D, Krieger JW, 2017, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/28834797/",
    "confidence": "strong (consistent meta-analytic finding)"
  },
  {
    "id": "TRAIN-07",
    "section": "TRAINING STIMULUS",
    "claim": "The 2026 ACSM position stand, an overview of 137 systematic reviews (more than 30,000 participants), found that voluntary strength was enhanced by heavier loads (≥80% 1RM), a complete range of motion, 2–3 sets, placement at the beginning of sessions and at least 2 sessions per week, and that hypertrophy was enhanced by higher volumes (≥10 sets per week) and eccentric overload. Training to momentary failure, equipment type, exercise complexity, set structure, time under tension, blood-flow restriction and periodization did not consistently affect outcomes, and healthy adults should perform progressive resistance training.",
    "use": "The current official baseline to anchor any training prescription.",
    "source": "Currier BS, D'Souza AC, Singh MAF, et al., 2026, Medicine and Science in Sports and Exercise (ACSM Position Stand)",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12965823/",
    "confidence": "strong (official position stand, overview of reviews)"
  },
  {
    "id": "TRAIN-08",
    "section": "TRAINING STIMULUS",
    "claim": "The 2009 ACSM position stand on progression recommends a 2–10% load increase when the current load can be performed for one to two repetitions over the desired number. For intermediate and advanced lifters it recommends 1–12RM in a periodized fashion with eventual emphasis on heavy 1–6RM loading and 3–5 min rests for strength, emphasis on 6–12RM with 1–2 min rests for hypertrophy, and training frequencies of 2–3 (novice), 3–4 (intermediate) and 4–5 (advanced) days per week.",
    "use": "A concrete progression rule (\"+2–10% once you beat the rep target by 1–2\"). Note that newer evidence favours rests longer than 1 min for hypertrophy (TRAIN-09, TRAIN-10).",
    "source": "American College of Sports Medicine, 2009, Medicine and Science in Sports and Exercise",
    "url": "https://pubmed.ncbi.nlm.nih.gov/19204579/",
    "confidence": "moderate (older consensus, partly updated by TRAIN-07)"
  },
  {
    "id": "TRAIN-09",
    "section": "TRAINING STIMULUS",
    "claim": "In 21 resistance-trained young men doing 3 sets of 8–12RM on 7 exercises, 3 times a week for 8 weeks, 3-min rests produced greater squat and bench press 1RM gains and greater anterior-thigh muscle thickness than 1-min rests.",
    "use": "Short rests can quietly cut the productive work in each session; resting around 3 minutes on big compound lifts, as tested here, is a safe default.",
    "source": "Schoenfeld BJ, Pope ZK, Benik FM, et al., 2016, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26605807/",
    "confidence": "moderate (single randomized trial)"
  },
  {
    "id": "TRAIN-10",
    "section": "TRAINING STIMULUS",
    "claim": "A Bayesian meta-analysis of 9 studies (19 measurements) suggests a small hypertrophic benefit to rest intervals longer than 60 s, possibly through less loss of volume load, but no appreciable difference once rests exceed 90 s; stopping sets short of failure or at failure did not change this.",
    "use": "Resting at least 60–90 s keeps reps up; beyond that, rest length is unlikely to be what is holding size back.",
    "source": "Singer A, Wolf M, Generoso L, et al., 2024, Frontiers in Sports and Active Living",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11349676/",
    "confidence": "moderate (small number of studies, high heterogeneity)"
  },
  {
    "id": "TRAIN-11",
    "section": "TRAINING STIMULUS",
    "claim": "A meta-analysis of 16 studies found full range-of-motion training produced greater gains than partial range of motion in muscle strength (ES 0.56) and lower-limb hypertrophy (ES 0.88), with no clear difference in muscle architecture.",
    "use": "Shrinking range of motion as loads climb is a real cost, especially for legs.",
    "source": "Pallarés JG, Hernández-Belmonte A, Martínez-Cava A, et al., 2021, Scandinavian Journal of Medicine and Science in Sports",
    "url": "https://pubmed.ncbi.nlm.nih.gov/34170576/",
    "confidence": "moderate (16 studies; most partials studied were not at long muscle lengths, see TRAIN-12)"
  },
  {
    "id": "TRAIN-12",
    "section": "TRAINING STIMULUS",
    "claim": "In 30 resistance-trained people whose arms were randomly assigned to lengthened partial repetitions or full range of motion for 8 weeks of upper-body training, gains in elbow-flexor and elbow-extensor thickness and in 10RM lat pulldown were similar between conditions. The authors conclude that trainees seeking size should emphasize the stretched position, through full range of motion or lengthened partials.",
    "use": "The partials that cost growth are the ones that cut out the stretched position; partials kept in the stretch performed like full reps here.",
    "source": "Wolf M, Androulakis Korakakis P, Piñero A, et al., 2025, PeerJ",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11829627/",
    "confidence": "emerging (one within-person trial, upper body only)"
  },
  {
    "id": "TRAIN-13",
    "section": "TRAINING STIMULUS",
    "claim": "In 30 untrained college-aged men training 3 times a week for 8 weeks (4 sets of 8–12 reps), focusing internally on contracting the target muscle increased elbow-flexor thickness more than an external, outcome-focused cue (12.4% vs 6.9%); quadriceps thickness changes were similar.",
    "use": "For an isolation exercise on a lagging muscle, cueing \"feel the target muscle\" may add growth; do not extend it to heavy compound lifts or trained lifters as a fact.",
    "source": "Schoenfeld BJ, Vigotsky A, Contreras B, et al., 2018, European Journal of Sport Science",
    "url": "https://pubmed.ncbi.nlm.nih.gov/29533715/",
    "confidence": "emerging (single study, untrained men, arms only)"
  },
  {
    "id": "TRAIN-14",
    "section": "TRAINING STIMULUS",
    "claim": "In 39 resistance-trained young adults (29 men, 10 women) on a 9-week high-volume program, a 1-week complete break from training at the midpoint produced no difference in lower-body hypertrophy, local endurance or power compared with continuous training, while continuous training produced greater isometric and dynamic lower-body strength gains.",
    "use": "A week completely off is not a growth hack; deloads are for managing fatigue, and a strength-focused user loses a little by stopping entirely.",
    "source": "Coleman M, Burke R, Augustin F, et al., 2024, PeerJ",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10809978/",
    "confidence": "emerging (single trial; tested full cessation, not a reduced-load deload)"
  },
  {
    "id": "STRESS-01",
    "section": "STRESS AND DIET QUALITY",
    "claim": "Among 135 undergraduates in 12-week weight-training classes (twice a week), those reporting low life-event stress gained significantly more bench press and squat 1RM than those reporting high stress; social support was unrelated to strength gains.",
    "use": "Life stress is a legitimate reason training stops paying; it is not a lack of willpower.",
    "source": "Bartholomew JB, Stults-Kolehmainen MA, Elrod CC, Todd JS, 2008, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/18545186/",
    "confidence": "emerging (observational, students, median split)"
  },
  {
    "id": "STRESS-02",
    "section": "STRESS AND DIET QUALITY",
    "claim": "In 31 resistance-training students, higher life-event stress and higher perceived stress were associated with slower recovery of maximal isometric force, energy, fatigue and soreness over the 96 h after a heavy leg-press session, even after adjusting for fitness, workload and training experience.",
    "use": "In high-stress periods, plan more recovery between hard sessions for the same muscles rather than adding volume.",
    "source": "Stults-Kolehmainen MA, Bartholomew JB, Sinha R, 2014, Journal of Strength and Conditioning Research",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24343323/",
    "confidence": "emerging (n = 31, observational design)"
  },
  {
    "id": "DIET-01",
    "section": "STRESS AND DIET QUALITY",
    "claim": "Twenty weight-stable adults admitted to the NIH Clinical Center ate ultra-processed or unprocessed diets for 2 weeks each, matched for presented calories, energy density, macronutrients, sugar, sodium and fibre. On the ultra-processed diet they ate 508 kcal/day more (carbohydrate +280, fat +230, protein −2 kcal/day) and gained 0.9 kg, versus losing 0.9 kg on the unprocessed diet.",
    "use": "Diet \"cleanliness\" acts mainly through how much it makes people eat: an ultra-processed-heavy diet can add about 500 kcal a day, which explains a bulk that turns into fat gain or a cut that does not move.",
    "source": "Hall KD, Ayuketah A, Brychta R, et al., 2019, Cell Metabolism",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7946062/",
    "confidence": "strong (tightly controlled inpatient randomized crossover, though short)"
  },
  {
    "id": "DIET-02",
    "section": "STRESS AND DIET QUALITY",
    "claim": "A meta-analysis of 11 observational studies (19,954 participants) found that a higher Dietary Inflammatory Index score was associated with higher odds of sarcopenia (OR 1.16), rising 1.22-fold per 1-point increase in the score.",
    "use": "Only as weak supporting context, mainly for older users; there is no direct evidence here that \"inflammatory\" foods slow muscle growth in healthy lifters.",
    "source": "Diao H, Yan F, He Q, et al., 2023, Nutrients",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9824141/",
    "confidence": "emerging (observational associations, mostly older populations)"
  },
  {
    "id": "AGE-01",
    "section": "AGE",
    "claim": "A meta-analysis of 47 studies (1,079 adults aged 50 or older) found resistance training increased strength by 29% (leg press), 24% (chest press), 33% (knee extension) and 25% (lat pull), with higher-intensity training associated with greater improvement.",
    "use": "Older users still gain substantial strength; intensity, not caution, drives the result.",
    "source": "Peterson MD, Rhea MR, Sen A, Gordon PM, 2010, Ageing Research Reviews",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC2892859/",
    "confidence": "strong (meta-analysis; heterogeneous studies)"
  },
  {
    "id": "AGE-02",
    "section": "AGE",
    "claim": "A meta-analysis of 49 studies (1,328 adults aged 50 or older) found resistance training increased lean body mass by 1.1 kg on average (95% CI 0.9–1.2); higher-volume programs produced larger gains, and older individuals gained less.",
    "use": "Set realistic expectations for older users (about 1 kg of lean mass on average across the pooled programs) and lean on volume.",
    "source": "Peterson MD, Sen A, Gordon PM, 2011, Medicine and Science in Sports and Exercise",
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC2995836/",
    "confidence": "strong (meta-analysis; high heterogeneity, I² = 84%)"
  },
  {
    "id": "AGE-03",
    "section": "AGE",
    "claim": "The PROT-AGE study group recommends at least 1.0–1.2 g protein/kg/day for people over 65, at least 1.2 g/kg/day for those who are exercising or otherwise active, and 1.2–1.5 g/kg/day for most older adults with acute or chronic disease; people with severe kidney disease (eGFR below 30) who are not on dialysis are an exception and may need to limit protein.",
    "use": "Protein floor for older users, with the kidney caveat (refer to their doctor if relevant).",
    "source": "Bauer J, Biolo G, Cederholm T, et al., 2013, Journal of the American Medical Directors Association",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23867520/",
    "confidence": "strong (expert consensus position)"
  },
  {
    "id": "AGE-04",
    "section": "AGE",
    "claim": "A retrospective analysis found that muscle protein synthesis plateaued after a single protein dose of 0.40 ± 0.19 g/kg body mass in older men (about 71 years) versus 0.24 ± 0.06 g/kg in younger men (about 22 years) (p = .055), or 0.60 vs 0.25 g/kg of lean body mass (p < .01).",
    "use": "Older lifters need larger protein servings per meal (about 0.4 g/kg) to get the full response.",
    "source": "Moore DR, Churchward-Venne TA, Witard O, et al., 2015, Journals of Gerontology Series A",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25056502/",
    "confidence": "moderate (retrospective pooled acute data, men only)"
  }
];

/** how the report model must use the evidence */
export const EVIDENCE_RULES: string[] = [
  "1. This file is the only evidence you may cite. Cite by ID in square brackets, e.g. [CARDIO-10]. Never cite a study, guideline, number or author that is not in this file, and never add numbers beyond what an entry's Claim states (simple arithmetic on the user's own numbers is fine, shown as an estimate).",
  "2. Keep the population and conditions attached to every number (\"in 22 resistance-trained men…\", \"in adults over 50…\"). Do not present findings from older, untrained or endurance populations as if they were measured on this user.",
  "3. Match the wording to Confidence: strong = state plainly; moderate = \"the best evidence suggests\"; emerging = \"early / small-study evidence suggests\". Never make an emerging entry the sole basis of a top-priority fix.",
  "4. \"Use in report\" lines are coaching guidance for applying the evidence, not study results. Do not quote them as findings.",
  "5. Nothing listed under \"Contested / do not state as fact\" may be stated as fact. If it comes up, say the evidence is mixed or missing.",
  "6. No diagnosis and no medical claims. Where symptoms appear (dizziness, confusion, palpitations, cramps that do not settle), say symptoms like these are a reason to see a doctor.",
  "7. The user's answers are self-reported estimates; present conclusions as \"likely\", not certain."
];

/** claims that must never be stated as fact */
export const CONTESTED: string[] = [
  "White salt residue or stains on skin or clothing reliably identify a \"salty sweater\": only commercial hydration-brand pages say so; no peer-reviewed or official source was found, and residue can also reflect sheer sweat volume.",
  "Salt loss causes exercise cramps: mixed. Five cramp-prone college football players lost about twice the sweat sodium of 5 matched teammates (Stofan et al. 2005, https://pubmed.ncbi.nlm.nih.gov/16521848/), but SWEAT-08 found no electrolyte or body-weight differences in 210 triathletes and SWEAT-07 calls cramps multifactorial.",
  "Sodium or electrolyte drinks increase strength, the \"pump\" or muscle growth (e.g., via cell swelling): not verified in humans; do not claim.",
  "Lifters should add lots of salt: blanket advice is not supported. The general adult guideline remains under 2,300 mg sodium a day (FDA, https://www.fda.gov/food/nutrition-education-resources-materials/sodium-your-diet); heavy sweaters' needs are individual (SWEAT-01, SWEAT-04).",
  "Raising VO2max will increase the weekly volume a trained lifter can recover from, or their hypertrophy: plausible from CARDIO-02 to 05 and CARDIO-09, but no trial in trained lifters has tested it.",
  "Heavy leg training \"counts as your cardio\": squat sets can briefly reach near-maximal heart rate and oxygen uptake (CARDIO-06), but heart rate during lifting overstates aerobic metabolism (CARDIO-07); no entry here shows lifting alone matches dedicated aerobic training for fitness.",
  "\"Cardio kills gains\": contradicted at normal doses (CARDIO-10). The idea traces to a 1980 study combining 5 strength and 6 endurance sessions a week, in which strength levelled off after week 7 and declined in weeks 9–10 (Hickson 1980, https://pubmed.ncbi.nlm.nih.gov/7193134/); do not generalize that load to normal lifters.",
  "An \"inflammatory\" or ultra-processed diet directly slows muscle growth: no direct evidence in healthy lifters; DIET-02 is observational sarcopenia data, and DIET-01 works through extra calories.",
  "Pre-workout low blood sugar explains weakness or brain fog: CARB-08 reports such symptoms are rarely linked to actually low glucose.",
  "Typical lifting sessions deplete glycogen enough to limit growth: partial depletion is documented (CARB-01, CARB-02), but CARB-03 argues true depletion is unlikely and growth signalling is unaffected.",
  "A specific number of sleep hours below which muscle growth stops: only acute synthesis and diet-phase data exist (SLEEP-03, 04, 06); no long-term hypertrophy trial in lifters.",
  "Irregular sleep timing (social jet lag) directly impairs lifting gains: only general health and performance consensus exists (SLEEP-07).",
  "Sleep-related testosterone drops reduce muscle gain: one week of 5-h nights lowered daytime testosterone by 10–15% in 10 young men (Leproult & Van Cauter 2011, https://pmc.ncbi.nlm.nih.gov/articles/PMC4445839/), but no muscle outcome was measured; do not turn hormone changes into hypertrophy claims.",
  "Habitual caffeine users lose its performance benefit (tolerance): CAFF-01 says habitual intake \"may play a role\"; not established.",
  "Moderate drinking (a drink or two) kills gains: the muscle data use 1–1.5 g/kg doses (ALC-01, ALC-02); long-term effects of low intake on hypertrophy are unknown.",
  "A deload week boosts growth by \"resensitizing\" muscle: TRAIN-14 found no hypertrophy benefit from a week off and smaller strength gains.",
  "The mind-muscle connection builds more muscle in trained lifters or on heavy compound lifts: TRAIN-13 tested untrained men on arm and leg exercises only."
];
